### DISCUSSION TITLE
How do postcss-nesting work now with the 2024-02 edition?

### DISCUSSION THREAD

**Discussion by felixsanz** [csstools/postcss-plugins#1474] [Q&A] [answered]
Hi there! I have this CSS code that works fine with the 2021 edition:

```css
      & :global(li) {
        &:global(.visible > a) {
          color: var(--color-primary);
        }

        &:global(:not(.visible) > a:hover span) {
          color: var(--color-opposite);
        }

        & :global(a) {
          width: 100%;
          display: inline-block;
          padding: 0.5rem 0;
          font-weight: 600;
        }
      }
```

It's been always working fine inside `.astro` files. But now with the 2024-02 edition I can't make it work. Any idea what is the syntax I need to add? Or this is an issue with astro?

Thanks!

**Comment by romainmenke** [comment]
Hi @felixsanz,

From that snippet alone I am unable to say what could be the cause of the difference.

Do you have a minimal but complete repro?

-----

I suspect it might be caused by wrapping in `:is()`.

`:global` isn't a standard selector, so likely other tools transpile this?
Maybe they can't transpile it when it is wrapped in `:is()`

See how many `:is()` selectors are created:

[demo](https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyLmZvbyUyMC5iYXIlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI2JTIwJTNBZ2xvYmFsKGxpKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjYlM0FnbG9iYWwoLnZpc2libGUlMjAlM0UlMjBhKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb2xvciUzQSUyMHZhcigtLWNvbG9yLXByaW1hcnkpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI2JTNBZ2xvYmFsKCUzQW5vdCgudmlzaWJsZSklMjAlM0UlMjBhJTNBaG92ZXIlMjBzcGFuKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb2xvciUzQSUyMHZhcigtLWNvbG9yLW9wcG9zaXRlKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyNiUyMCUzQWdsb2JhbChhKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB3aWR0aCUzQSUyMDEwMCUyNSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBkaXNwbGF5JTNBJTIwaW5saW5lLWJsb2NrJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHBhZGRpbmclM0ElMjAwLjVyZW0lMjAwJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGZvbnQtd2VpZ2h0JTNBJTIwNjAwJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTdEJTIyJTJDJTIyY29uZmlnJTIyJTNBJTdCJTIyYnJvd3NlcnMlMjIlM0ElNUIlMjIlM0UlMjAwLjIlMjUlMjBhbmQlMjBub3QlMjBkZWFkJTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTAlMkMlMjJzdGFnZSUyMiUzQTIlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCU3RCU3RA==)

```css

        :is(:is(.foo .bar) :global(li)):global(.visible > a) {
          color: var(--color-primary);
        }
:is(:is(.foo .bar) :global(li)):global(:not(.visible) > a:hover span) {
          color: var(--color-opposite);
        }
:is(:is(.foo .bar) :global(li)) :global(a) {
          width: 100%;
          display: inline-block;
          padding: 0.5rem 0;
          font-weight: 600;
        }
```
