### DISCUSSION TITLE
Replacing importFrom with postcss-global-data in webpack config (for custom properties)

### DISCUSSION THREAD

**Discussion by gpspake** [csstools/postcss-plugins#879] [General]
I'm using the `importFrom` option with `postcss-preset-env` to make css custom properties available globally. `importFrom` is removed in the latest version and [postcss-global-data seems to be the recommended alternative](https://github.com/csstools/postcss-plugins/discussions/192?sort=top). I'm trying to update my configuration to use it but it's not working for me and I'm having a hard time finding docs and examples.

Currently, all of my custom properties in a javascript file like this:
`variables.js`
```javascript
'use strict';

var colors = {
  '--blue': '#1cbfff',
  '--dark-green': '#00c174',
  // ...
};

var thematicColors = {
  '--status-positive-hc': colors['--dark-green'],
  // ...
};

var settings = {
  '--gutter': '20px',
  '--container-width': '1200px',
  // ...
};

exports.colors = colors;
exports.thematicColors = thematicColors;
exports.settings = settings;
exports.all = Object.assign({}, colors, thematicColors, settings);

```
And I import them in my config using `importFrom` like this:
`webpack.config.babel.js`
```javascript
const _customProperties = require('./variables');

const customProperties = _customProperties.all;

module.exports = {
  entry: {...},
  output: {...},
  resolve: {...},
  plugins: plugins.concat([...]),
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          { loader: MiniCssExtractPlugin.loader },
          { loader: 'css-loader', ... },
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [
                  postcssImport,
                  postcssPresetEnv({
                    importFrom: [
                      {
                        customProperties
                      }
                    ],
                    stage: 0,
                    preserve: false
                  }),
                  postcssNested
                ]
              }
            }
          }
        ]
      },
      ...
    ]
  },
  devtool: 'cheap-module-source-map'
};
```
That makes the custom properties available as fallbacks, basically so if any of them are used in our css, they get resolved correctly. 

So how do I replace this set up with `postcss-global-data`? Here's what I've tried based on the [postcss-global-data docs](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-global-data#readme)
First I moved the custom properties in to a css file:
`css-custom-properties.css`
```css
:root {
  /* colors */
  --blue: #1cbfff;
  --dark-green: #00c174;

  /*var thematicColors = {*/
  --status-positive-hc: --dark-green;

  /*var settings = {*/
  --gutter: 20px;
}

```
Then I changed my config to pass that file to `postcss-global-data`

`webpack.config.babel.js`
```javascript
const postcssGlobalData = require('@csstools/postcss-global-data');

module.exports = {
  ...
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          ...
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [
                  postcssImport,
                  postcssPresetEnv({
                    // importFrom: [
                    // {
                    //   customProperties
                    // }
                    // ],
                    stage: 0,
                    preserve: false
                  }),
                  postcssNested,
                  postcssGlobalData({
                    files: ['./css-custom-properties.css']
                  })
                ]
              }
            }
          }
        ]
      },
      ...
    ]
  },
  ...
};
```
I've also tried changing the plugin order in case that's the problem...
`webpack.config.babel.js`
```javascript
const postcssGlobalData = require('@csstools/postcss-global-data');

module.exports = {
  ...
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          ...
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [
                  postcssGlobalData({
                    files: ['./css-custom-properties.css']
                  }),
                  postcssImport,
                  postcssPresetEnv({
                    stage: 0,
                    preserve: false
                  }),
                  postcssNested
                ]
```

Note: In case the path could be a factor, the css file is in the same directory as the webpack config. The file structure looks like this
```
/
|__webpack.config.babel.js
|__css-custom-properties.css
```
Note: My IDE is showing this error which might be a clue. Maybe I'm misusing the plugin.
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/3385690/221624315-04031246-6359-47f3-8593-ca9109f8f54e.png">
Other plugins aren't showing this error:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/3385690/221624562-56aea182-747b-4ce8-b1ec-b0af14d915bc.png">

**Comment by romainmenke** [comment]
Hi @gpspake, thank you for starting this discussion!

Can you take a look at this example : 
https://github.com/csstools/postcss-plugins/pull/880

When I run `npm run build` I see :

<img width="785" alt="Screenshot 2023-02-27 at 18 24 44" src="https://user-images.githubusercontent.com/11521496/221636188-e1c7f51c-5e40-4b63-b7d5-e10d5762ee86.png">

The plugins seem to work well in a Webpack context :

CSS :

```css
.a {
	color: var(--color);
}
```

props :

```css
:root {
	--color: pink;
}
```

Webpack config :

```js
const path = require('path');
const postcssGlobalData = require('@csstools/postcss-global-data');

module.exports = {
	mode: 'production',
	entry: './index.js',
	target: 'node',
	optimization: {
		minimize: false,
	},
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'bundle.cjs',
	},
	module: {
		rules: [
			// We document how to use our plugins together with Webpack.
			// This test validates this documentation.
			{
				test: /\.css$/i,
				use: [
					'style-loader',
					{
						loader: 'css-loader',
						options: { importLoaders: 1 },
					},
					{
						loader: 'postcss-loader',
						options: {
							postcssOptions: {
								plugins: [
									postcssGlobalData({
										files: ['./props.css'],
									}),
									[
										'postcss-preset-env',
										{
											stage: 0,
											preserve: false,
										},
									],
								],
							},
						},
					},
				],
			},
		],
	},
};
```

----

Is there a difference with your setup that I am overlooking?

**Comment by gpspake** [comment]
Thanks for the quick response @romainmenke 🙂 
That looks to be the same as what I have but I'm not seeing what you posted in that screenshot in my bundle 😕. 

The css variables and the other css files they're used in are actually (mostly) in another library I'm importing which adds a layer of confusion. I'll try to dig in to my configuration some more and compare some things.

**Reply by romainmenke** [reply]
Forgot to ask, but are you seeing any error messages?

I would expect `postcss-global-data` to throw an exception when it has a file path but is unable to locate the file.

Maybe also good to test this with a bogus path to make sure that errors are reported to you.

**Reply by gpspake** [reply]
Good call. Changing the path to a non-existent file (abc.css) throws an error (Well a bunch of errors) like:
```
ERROR in ./src/views/reports/reports.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, open '/Users/.../client/abc.css'
```
So that confirms that the plugin is installed properly, working and finding the file, I think.

Here's a sample of what `css-custom-properties` looks like:
```css
:root {
  /* colors */
  --dark-blue: #0077c3;
  --dark-green: #00c174;

  /* thematicColors */
  --status-positive-hc: var(--dark-green);
  --anchor-color: var(--dark-blue);

  /* typography */
  --sans: "HCo Gotham SSm; sans-serif";
  --gauge: "Gauge; HCo Gotham SSm; sans-serif";
  --mono: "Source Code Pro; monospace";
  --font-weight-bold: 700;
  --font-weight-medium: 500;
  --font-weight-normal: 400;
  --font-weight-light: 100;
}
```

Based on our config, webpack just outputs a single css file. If I run yarn build with the original `importFrom` config, I can see that all of the custom properties have been replaced with their values:
```css
.modal__overlay__uqT4u.modal__dark__VMuUe {
    background-color: color(#000000 alpha(90%));
  }
```

If I switch to the `postcss-global-data` config, it just shows the `var()` statements
```css
.modal__overlay__uqT4u.modal__dark__VMuUe {
    background-color: color(var(--black) alpha(90%));
  }
```
