### ISSUE TITLE
[PostCSS Nesting] Parsing error using + combinator

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-plugins#1]
Hi, i have the following issue using the `@nest` at-rule.

Using the `>` combinator inside a `@nest` selector it works fine. This snippet works as expected:

```css
.Hint {
  position: absolute;
  color: blue

  @nest .Field:invalid > & {
    color: red;
  }
}

/*
	RETURNS
	.Hint {
	  position: absolute
	}
	
	.Field:invalid > .Hint {
	    color: red;
	    font-weight: 2
	}
*/
```

But this returns a syntax error:

```css
.Hint {
  position: absolute;
  color: blue

  @nest .Field:invalid + & {
    color: red;
  }
}

/*
	SHOULD RETURNS
	.Hint {
	  position: absolute
	}
	
	.Field:invalid + .Hint {
	    color: red;
	    font-weight: 2
	}
*/
```

> Module build failed: ParserError: Syntax Error at line: 1, column 16 at Generator.next (<anonymous>)

Now i know i could write the selector in another way to make it work, but i think it's just a sort of parsing bug because both are valid combinators, and i want to keep consistency using one syntax (using @nest).

This issue is cloned from the original plugin repository:
https://github.com/jonathantneal/postcss-nesting/issues/67
