### ISSUE TITLE
css-has-pseudo is not working when hovering on child

### ISSUE THREAD

**Issue by abdallahz3** [csstools/postcss-plugins#100]
Hi,
I have css like this
```css
.wrapper:has(> input:hover) {
  /* style links that contain an image */
  background-color: green;
}
```
When hovering on the input nothing happens, but clicking on the input, the wrapper turns green, the same behaviour happens 
if we replaced input:hover with button:hover.
if we replaced input:hover with p:hover for example, nothing happens

I'm using css-has-pseudo version 3.0.1

here is the html just in case
```html
<div className="wrapper">
  <input />
</div>
```

**Comment by romainmenke** [comment]
Note : 

```bash
pbpaste | npx -y css-has-pseudo
```

Input

```css
.wrapper[\:has\(\%3E\%20input\:hover\)] {
  /* style links that contain an image */
  background-color: green;
}
```

Output

```css
.wrapper:has(> input:hover) {
  /* style links that contain an image */
  background-color: green;
}
```
