### ISSUE TITLE
[focus-within] Duplicate selector generated

### ISSUE THREAD

**Issue by IlyaSemenov** [csstools/postcss-plugins#1040]
### Bug description

`postcss-focus-within` generates duplicate selectors if the source CSS has multiple selectors in a rule.

Besides, there is no point in generating second rule at all. I would expect a single rule (or two when/if #1039 is implemented).

### Source CSS

```css
.foo, .bar, .baz:focus-within { display: block }
```

### Expected CSS

```css
.foo, .bar, .baz:focus-within, .baz[focus-within].js-focus-within, .js-focus-within .baz[focus-within] { display: block }
```

or, ideally (with #1039):

```css
.foo, .bar, .baz[focus-within].js-focus-within, .js-focus-within .baz[focus-within] { display: block }
.baz:focus-within { display: block }
```

### Actual CSS

```css
.foo, .bar, .baz[focus-within].js-focus-within, .js-focus-within .baz[focus-within] { display: block }
.foo, .bar, .baz:focus-within { display: block }
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Focus Within

### Plugin version

8.0.0

### What OS are you experiencing this on?

macOS

### Node Version

16.19.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @IlyaSemenov,

Please see the readme : https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-focus-within#preserve

It describes the `preserve` option.

You can choose to either preserve or remove the original CSS.

**Comment by IlyaSemenov** [comment]
@romainmenke With `preserve` option, the original `:focus-within` is removed completely:

```css
.foo, .bar, .baz[focus-within].js-focus-within, .js-focus-within .baz[focus-within] { display: block }
```

This is not what I would expect as a developer. I would expect modern browser to continue using `:focus-within` as they always did.

**Comment by IlyaSemenov** [comment]
> I am not sure what you are asking here.

I'm asking to change the plugin to stop generating duplicate rules that serve no purpose.

I've carefully filled "Source CSS" and "Expected CSS" sections above with a minimal example.

--- 

> Is there anything broken because of the CSS that is generated?

No. It's just that the generated CSS is sub-par due to duplication of selectors that have no relation to `:focus-within`. If it was inserting the selectors 1000 times, nothing would break either.

If that's not something that bothers anyone, you may of course close the issue as not planned.

**Comment by romainmenke** [comment]
Source : 

```css
.foo, :focus-within {
  display: block
}
```

This is a selector list with two selectors.
One class selector and one pseudo selector.

As mentioned in the other issue, selector lists are not forgiving.
In a browser without native support for the pseudo selector, the entire rule would be ignored.

This CSS means :
> match `.foo` or `:focus-within` if you understand `:focus-within`

-------------

If the plugin generated a fallback that looks like this :

```css
.foo, :focus-within, [focus-within] {
  display: block
}
```

It would mean : 
> match `.foo`, `[focus-within]` or `:focus-within` if you understand `:focus-within`

This would defeat the purpose of the plugin as nothin would ever be matched in browsers without native support.

--------

If the plugin generated a fallback that looks like this :

```css
.foo, [focus-within] {
  display: block
}

:focus-within {
  display: block
}
```

It would mean : 
> match `.foo` or `[focus-within]`
> match `:focus-within`

This would be similar to the original CSS but not exactly the same.
It would however go against the principle of the `preserve` option.

When `preserve` is true we are not supposed to be editing the original rule or it's selector.
