### ISSUE TITLE
`@media (color-gamut: ...)` checks for color fallbacks

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#1049]
```css
.foo {
  color: oklch(...)
}

/* becomes */

.foo {
  color: rgb(...);
  color: color(display-p3 ...);
}
```

But this doesn't take into account the hardware capabilities of the current device.

Ideal output :

```css
.foo {
  color: oklch(...)
}

/* becomes */

.foo {
  color: rgb(...);
}

@media (color-gamut: display-p3) {
  .foo {
    color: color(display-p3 ...);
  }
}
```

----

This requires similar tricks as progressive custom properties.

**Comment by ai** [comment]
We can think about it as a polyfill, because current browsers violate CSSWG spec and do gamut correction in a wrong way.

So we will fix compatibility issue.

**Comment by romainmenke** [comment]
Exactly :)

For me this is very similar to [`postcss-progressive-custom-properties`](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-progressive-custom-properties#postcss-progressive-custom-properties-)

```css
:root {
	/* fallback */
	--a-color: red;
	/* progressive enhancement */
	--a-color: oklch(40% 0.234 0.39 / var(--opacity-50));
}

/* becomes */

:root {
	--a-color: red;
}

@supports (color: oklch(0% 0 0)) {
	:root {
		--a-color: oklch(40% 0.234 0.39 / var(--opacity-50));
	}
}
```

But then not for CSS variables and with `@supports` but for all wide gamut colors and with `@media`.
