### ISSUE TITLE
color-mix plugin doesn't give expected results for 'in oklab'

### ISSUE THREAD

**Issue by snoopen** [csstools/postcss-plugins#1055]
### Bug description

I'm using the postcss-color-mix-function plugin in a tailwindcss project. Unfortunately I am not seeing the colors I expected.

The color I separately calculated matches what the latest version of Chrome outputs with the same css. I have also checked against [this blog article](https://raphlinus.github.io/color/2021/01/18/oklab-critique.html) that has a color gradient tool for multiple color spaces.

### Source CSS

```css
.bg-blue-50 {
  background-color: color-mix(in oklab, #09232C 50%, white);
}
```

### Expected CSS

```css
.bg-blue-50 {
  background-color: rgb(123 137 142);
}
```

### Actual CSS

```css
.bg-blue-50 {
  background-color: rgb(112, 139, 150);
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Plugin version

2.0.0

### Node Version

16.17.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
