### ISSUE TITLE
An trouble of the combination `postcss-custom-properties` and `postcss-custom-media`

### ISSUE THREAD

**Issue by penpen-365** [csstools/postcss-plugins#1075]
### Bug description

Custom variables within media queries are not being resolved and are being output as is, causing expected styles not to be applied in responsive mode (PC).

### Source CSS

  ```CSS

/* ===================  Variables =================== */

/* -------- media query -------- */

/* portrait */
@custom-media --tablet-view (min-width: 768px);

/* landscape */
@custom-media --pc-view (min-width: 1530px);

:root{ /* -------- font -------- */
  --12px: 0.750rem;
  --14px: 0.875rem;
  --15px: 0.9375rem;
  --18px: 1.125rem;
  --20px: 1.25rem;
  --28px: 1.75rem;
  --36px: 2.25rem;
  --50px: 3.125rem;
  --90px: 5.625rem;
  --default-font: roboto, meiryo, helvetica, sans-serif;
  --default-fontsize: var(--15px);
  --default-lineheight: calc(18 / 15);

  /* -------- color -------- */
  --theme-color1: #5e3db3;
  --theme-color2: #090c35;
  --theme-color3: #f5f4f9;
  --theme-color4: #e7e7e7;
  --theme-color5: #c2c2c2;
  --default-color: #000;
  --default-link-color: #5900ff;

  /* --dedault-border-color */
  --default-bg-color: #fff;

  /* -------- size -------- */
  --tablet-width: 768px;
  --pc-width: 1530px;
  --base-margin: 10px;
  --default-horizonal-space: 18px;

  --opacity: 0.75;

  /* -------- responsive -------- */
  @media (--tablet-view){
    --default-fontsize: var(--18px);
    --default-lineheight: calc(28 / 18);
  }

  @media (--pc-view){
    --default-horizonal-space: calc((100% - var(--pc-width)) / 2);
  }
}
```

### Expected CSS

```CSS
@media (--pc-view){
  --default-horizonal-space: calc(50% - 765px);
}
```

### Actual CSS

```CSS
@media (--pc-view){
  --default-horizonal-space: calc((100% - var(--pc-width)) / 2);
}
```

Besides, `var(--pc-width)` is not resolved.

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Extra config

```JS
import autoprefixer from "autoprefixer";
import calc from "postcss-calc";
import nested from "postcss-nested";
import customMedia from "postcss-custom-media";
import customProperties from "postcss-custom-properties";
import globalData from "@csstools/postcss-global-data";


export default {
  plugins: [
    nested(),
    autoprefixer(),
    globalData({
      files: [
        "src/assets/css/data/_variables.css",
      ],
    }),
    customMedia({
      preserve: false,
    }),
    customProperties({
      preserve: false,
    }),
    calc(),
  ],
};

```

### What plugin are you experiencing this issue on?

PostCSS Custom Media Queries, PostCSS Custom Properties, PostCSS Global Data

### Plugin version

"postcss-custom-media": "^10.0.0",     "postcss-custom-properties": "^13.2.1",

### What OS are you experiencing this on?

macOS

### Node Version

v20.4.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @penpen-365,

Thank you for reaching out.

I am not sure what the issue is here.

Can you clarify these parts :
- which CSS is relevant to your issue?
- can you remove all CSS that isn't relevant
- which files do you have?
- which CSS is part of which file?

------

Can you also look at this demo : 

https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiJAY3VzdG9tLW1lZGlhIC0tcGMtdmlldyAobWluLXdpZHRoOiAxNTMwcHgpO1xuXG46cm9vdHtcbiAgLS1wYy13aWR0aDogMTUzMHB4O1xuICBcbiAgQG1lZGlhICgtLXBjLXZpZXcpe1xuICAgIC8qIEEgY3VzdG9tIHByb3BlcnR5IGlzbid0IHRyYW5zcGlsZWQgKi8gXG4gICAgLS1kZWZhdWx0LWhvcml6b25hbC1zcGFjZTogY2FsYygoMTAwJSAtIHZhcigtLXBjLXdpZHRoKSkgLyAyKTtcblxuICAgIC8qIGEgcmVndWxhciBwcm9wZXJ0eSBpcyAqL1xuICAgIGFueS1yZWd1bGFyLXByb3A6IGNhbGMoKDEwMCUgLSB2YXIoLS1wYy13aWR0aCkpIC8gMik7XG4gIH1cbn0iLCJjb25maWciOnsiYnJvd3NlcnMiOlsiSUUgMTAiXSwibWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyI6MCwic3RhZ2UiOjIsImxvZ2ljYWwiOnsiaW5saW5lRGlyZWN0aW9uIjoibGVmdC10by1yaWdodCIsImJsb2NrRGlyZWN0aW9uIjoidG9wLXRvLWJvdHRvbSJ9fX0%3D

```css
@custom-media --pc-view (min-width: 1530px);

:root{
  --pc-width: 1530px;
  
  @media (--pc-view){
    /* A custom property isn't transpiled */ 
    --default-horizonal-space: calc((100% - var(--pc-width)) / 2);

    /* a regular property is */
    any-regular-prop: calc((100% - var(--pc-width)) / 2);
  }
}
```

This doesn't use `@csstools/postcss-global-data` but it illustrates how custom properties that contain `var()` functions aren't transpiled by `postcss-custom-property`.

They are transpiled because that plugin is intended as a polyfill for `var()`.  
It isn't something like sass variables, which are fully removed by a build tool.

**Comment by romainmenke** [comment]
@penpen-365 After taking a look at your project I think I understand the issue better.

I think you are running into this limitation : 

https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiJcbjpyb290e1xuICAvKiB0cnkgdW5jb21tZW50aW5nIHRoZSBuZXh0IGxpbmUgOiAqL1xuICAvKiAtLWZvbzogNXB4OyAqL1xuXG4gIEBtZWRpYSAobWluLXdpZHRoOiAzMDBweCl7XG4gICAgLS1mb286IDEwcHg7XG4gIH1cbn1cblxuLmJhciB7XG4gIHdpdGg6IHZhcigtLWZvbyk7XG59IiwiY29uZmlnIjp7ImJyb3dzZXJzIjpbIklFIDEwIl0sIm1pbmltdW1WZW5kb3JJbXBsZW1lbnRhdGlvbnMiOjAsInN0YWdlIjoyLCJsb2dpY2FsIjp7ImlubGluZURpcmVjdGlvbiI6ImxlZnQtdG8tcmlnaHQiLCJibG9ja0RpcmVjdGlvbiI6InRvcC10by1ib3R0b20ifSwicHJlc2VydmUiOmZhbHNlfX0%3D

```css

:root{
  /* try uncommenting the next line : */
  /* --foo: 5px; */

  @media (min-width: 300px){
    --foo: 10px;
  }
}

.bar {
  with: var(--foo);
}
```

We can not transpile custom property values that have been declared in `@media` rules.
Only those found directly in `html {}` or `:root {}` selectors.
