### ISSUE TITLE
justify-content:right; polyfill does not work

### ISSUE THREAD

**Issue by basicButtons** [csstools/postcss-plugins#1085]
### Bug description

justify-content:right; This css feature supportes chrome which version is not less 93. but when I set browsersListrc chrome > 70, postcss-preset-env doesn't polyfill this feature.

### Source CSS

```css
.copyInfoRow {
  display: flex;
  justify-content: right;
}
```

### Expected CSS

I dont know how to polyfill this feature

### Actual CSS

```css
.copyInfoRow {
  display: flex;
  justify-content: right;
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Extra config

```
iOS >= 7
Android >= 4
ChromeAndroid >= 40
UCAndroid >= 11
IE >= 6
edge >= 79
safari > 12.0
edge >= 79
> 0.25%
Chrome >= 70
```

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

```
"postcss-less": "^6.0.0",
"postcss-loader": "^5.2.0",
"postcss-preset-env": "^9.1.0",
```

### What OS are you experiencing this on?

macOS

### Node Version

18.16.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
