### ISSUE TITLE
Add percentage support to `opacity`

### ISSUE THREAD

**Issue by EvgenyOrekhov** [csstools/postcss-plugins#113]
```css
.foo {
  opacity: 50%;
}
```

should be transformed into

```css
.foo {
  opacity: 0.5;
}
```

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
