### ISSUE TITLE
postcss-custom-properties does not detect :root

### ISSUE THREAD

**Issue by tomsommer** [csstools/postcss-plugins#1149]
### Bug description

The `:root` selector is not detected by `postcss-custom-properties` if `:root` is combined with other selectors.
This is something Bootstrap does, so it breaks with all Bootstrap 5.3 css.

### Source CSS

```css
html {
  --color: red;
}

:root, [data-foo=bar] {
  --color-from-var: var(--color);
}

.color-from-var {
  color: red;
  color: var(--color);
}

.color-with-fallback {
  color: blue;
  color: var(--unknown-color, blue);
}

.color-from-var-from-var {
  color: var(--color-from-var);
}
```

### Expected CSS

```css
html {
  --color: red;
}

:root, [data-foo=bar] {
  --color-from-var: var(--color);
}

.color-from-var {
  color: red;
  color: var(--color);
}

.color-with-fallback {
  color: blue;
  color: var(--unknown-color, blue);
}

.color-from-var-from-var {
  color: red;
  color: var(--color-from-var);
}
```

### Actual CSS

```css
html {
  --color: red;
}

:root, [data-foo=bar] {
  --color-from-var: var(--color);
}

.color-from-var {
  color: red;
  color: var(--color);
}

.color-with-fallback {
  color: blue;
  color: var(--unknown-color, blue);
}

.color-from-var-from-var {
  color: var(--color-from-var);
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Custom Properties

### Plugin version

8.4.31

### Node Version

16.20.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment]
Hey @tomsommer thanks for reaching out!

I see the plugin version is rather old. I've tested your [Source CSS in the playground](https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiJodG1sIHtcbi0tY29sb3I6IHJlZDtcbn1cblxuOnJvb3QsIFtkYXRhLWZvbz1iYXJdIHtcbi0tY29sb3ItZnJvbS12YXI6IHZhcigtLWNvbG9yKTtcbn1cblxuLmNvbG9yLWZyb20tdmFyIHtcbmNvbG9yOiByZWQ7XG5jb2xvcjogdmFyKC0tY29sb3IpO1xufVxuXG4uY29sb3Itd2l0aC1mYWxsYmFjayB7XG5jb2xvcjogYmx1ZTtcbmNvbG9yOiB2YXIoLS11bmtub3duLWNvbG9yLCBibHVlKTtcbn1cblxuLmNvbG9yLWZyb20tdmFyLWZyb20tdmFyIHtcbmNvbG9yOiByZWQ7XG5jb2xvcjogdmFyKC0tY29sb3ItZnJvbS12YXIpO1xufSIsImNvbmZpZyI6eyJicm93c2VycyI6WyI%2BIDAuMiUgYW5kIG5vdCBkZWFkIl0sIm1pbmltdW1WZW5kb3JJbXBsZW1lbnRhdGlvbnMiOjAsInN0YWdlIjoyLCJsb2dpY2FsIjp7ImlubGluZURpcmVjdGlvbiI6ImxlZnQtdG8tcmlnaHQiLCJibG9ja0RpcmVjdGlvbiI6InRvcC10by1ib3R0b20ifSwiZmVhdHVyZXMiOnsibmVzdGluZy1ydWxlcyI6eyJub0lzUHNldWRvU2VsZWN0b3IiOmZhbHNlfX19fQ%3D%3D) and it seems to be creating the expected output.

Is that the plugin version or PostCSS Preset Env's one?

**Comment by Antonio-Laguna** [comment]
@tomsommer the version you report the plugin to be is `8.4.31` while we're now at `13.3.2`. Checking the versions `8.4.31` does not even exist. Could you double check?

**Comment by Antonio-Laguna** [comment]
Ok, let me run that test in isolation :)

**Comment by Antonio-Laguna** [comment]
So this is what I'm getting on that plugin alone:

```css
html {
	--color: red;
}

:root, [data-foo=bar] {
	--color-from-var: var(--color);
}

.color-from-var {
	color: red;
	color: var(--color);
}

.color-with-fallback {
	color: blue;
	color: var(--unknown-color, blue);
}

.color-from-var-from-var {
	color: red;
	color: var(--color-from-var);
}
```

Which looks as expected. Is there anything else running on your PostCSS pipeline?
