### ISSUE TITLE
oklab and oklch non-percentage values for lightness not supported in Safari 16.0 on iPhone 12

### ISSUE THREAD

**Issue by rsstiglitz** [csstools/postcss-plugins#1176]
### Bug description

Safari 16.0 on iPhone 12 does not seem to support normal number values for the lightness entry in `oklch` and `oklab` functions when at the same time using a variable in the `/` opacity addition. `@csstools/postcss-oklab-function` is not accounting for that when using `oklch` and `oklab` with a `/ var(--opacity)` opacity suffix and using the options `{"preserve": true}` because it inserts this `supports` rule:

```css
@supports (color: oklab(0% 0 0)) {
  /* ... */
}
```

This leads to this example not being polyfilled:

```css
span {
  color: oklch(0.5 0.5 0 / var(--opacity));
}
```

Three different ways to fix this, either adjust the supports rule to `@supports (color: oklab(0 0 0))` (without the percentage symbol; it works, I tried it), but this might break other environments which support only numbers and no percentage (are there any). Or, and I don't know if postcss plugins are able to do this, convert decimals in `oklab` and `oklch` functions to percentage values.

Third option is to make two `supports` rules, one with the percentage symbol and one without it.

### Source CSS

```
span {
  color: oklch(0.5 0.5 0 / var(--opacity));
}
```

### Expected CSS

```css
/* Either */

span {
  color: rgba(186, 0, 94, var(--opacity));
}

@supports (color: color(display-p3 0 0 0)) {
  span {
    color: color(display-p3 0.68273 0 0.36343 / var(--opacity));
  }
}

@supports (color: oklab(0 0 0)) {
  span {
    color: oklch(0.5 0.5 0 / var(--opacity));
  }
}

/* Or */

span {
  color: rgba(186, 0, 94, var(--opacity));
}

@supports (color: color(display-p3 0 0 0)) {
  span {
    color: color(display-p3 0.68273 0 0.36343 / var(--opacity));
  }
}

@supports (color: oklab(0% 0 0)) {
  span {
    color: oklch(50% 0.5 0 / var(--opacity));
  }
}
```

### Actual CSS

```css
span {
  color: rgba(186, 0, 94, var(--opacity));
}

@supports (color: color(display-p3 0 0 0)) {
  span {
    color: color(display-p3 0.68273 0 0.36343 / var(--opacity));
  }
}

@supports (color: oklab(0% 0 0)) {
  span {
    color: oklch(0.5 0.5 0 / var(--opacity));
  }
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS OKLab Function

### Plugin version

3.0.7

### What OS are you experiencing this on?

macOS

### Node Version

20.8.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
