### ISSUE TITLE
Can't use css-custom-property with relative color syntax 

### ISSUE THREAD

**Issue by albertoforni** [csstools/postcss-plugins#1221]
### Bug description

When trying to use a css-custom-property with the relative color syntax the output is unchanged.
See this [playground](https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTNBcm9vdCUyMCU3QiU1Q24lNUN0LS1tYWluQ29sb3IlM0ElMjAlMjMyMjIyMjIlM0IlNUNuJTdEJTVDbiU1Q25ib2R5JTIwJTdCJTVDbiUyMCUyMGJhY2tncm91bmQlM0ElMjByZ2IoZnJvbSUyMHZhcigtLW1haW5Db2xvciklMjByJTIwZyUyMGIlMjAlMkYlMjA2MCUyNSklM0IlNUNuJTdEJTIyJTJDJTIyY29uZmlnJTIyJTNBJTdCJTIyYnJvd3NlcnMlMjIlM0ElNUIlMjIlM0UlMjAwLjIlMjUlMjBhbmQlMjBub3QlMjBkZWFkJTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTAlMkMlMjJzdGFnZSUyMiUzQTAlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCUyQyUyMmZlYXR1cmVzJTIyJTNBJTdCJTIybmVzdGluZy1ydWxlcyUyMiUzQSU3QiUyMm5vSXNQc2V1ZG9TZWxlY3RvciUyMiUzQWZhbHNlJTdEJTdEJTJDJTIycHJlc2VydmUlMjIlM0FmYWxzZSU3RCU3RA==)

### Source CSS

```css
:root {
	--mainColor: #222222;
}

body {
  background: rgb(from var(--mainColor) r g b / 60%);
}
```

### Expected CSS

```css
:root {
	--mainColor: #222222;
}

body {
  background: rgb(34 34 34 / 60%);
}
```

### Actual CSS

```css
:root {
	--mainColor: #222222;
}

body {
  background: rgb(from var(--mainColor) r g b / 60%);
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Debug output

I don't see the plugin in the list so I tried `npx @csstools/csstools-cli postcss-preset-env minimal-example.css` with this output
```
:root {
	--mainColor: #222222;
}

body {
  background: rgb(from var(--mainColor) r g b / 60%);
}
```

### Plugin version

9.3.0

### Node Version

14.2.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR
