### ISSUE TITLE
Specificity error with svelte components

### ISSUE THREAD

**Issue by thebjorn** [csstools/postcss-plugins#1288]
### Bug description

`.btn:not(#\#)` has higher specificity than the svelte generated `.btn.svelte-<random>`, causing component styling to fail.

### Source CSS

src/index.css
```css
@layer core {
    .btn {
        background-color: green;
        color: white;
    }
}
```

src/app.pcss
```css
@import 'src/css/index.css';

@layer base {
    .btn {
        background-color: blue;
    }
}
```
src/+page.svelte
```html
<button class="btn">hello</button>

<style lang=postcss>
  .btn {
    background-color: red;
  }
</style>
```

### Expected CSS

The button should have red background.

### Actual CSS

The button has blue background.

### Playgound example

Example repo: https://github.com/thebjorn/pcssverify

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Cascade Layers

### Plugin version

4.0.2

### What OS are you experiencing this on?

Windows

### Node Version

21.5.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
