### ISSUE TITLE
Nested file resolution with design-tokens

### ISSUE THREAD

**Issue by osiler** [csstools/postcss-plugins#1293]
### What would you want to propose?

I have been getting a SvelteKit based toolchain working with PostCSS and [design tokens](https://github.com/amzn/style-dictionary) (inspired by the style-dictionary [complete template](https://github.com/amzn/style-dictionary/tree/main/examples/complete/tokens)). While everything is happy when using a flat file structure without nested token references, working with the complete example fails as I don't believe the ```@design-tokens``` can reference other Jsons. I understand that the design systems workflow is still relatively early, so thankyou for the plugin development.

### Suggested solution

You could collapse down the files in a directory and produce a large design-token Json file.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by osiler** [comment]
Hi, thanks for pointing that out. I think the area of the spec I am referring to is [here](https://tr.designtokens.org/format/#aliases-references) but I don't see where this specifies that aliases must be limited to within one file.

**Comment by romainmenke** [comment]
Maybe I misunderstood :)
Can you create a minimal reproduction?

**Comment by osiler** [comment]
Lets remove the svelte part for now, here is a minimal example.

E.g input.css
```css
@design-tokens url('test_base.json')  format('style-dictionary3');

/* Alias defined in brand, that links to test_base.json */
/* Uncomment this to demonstrate failed alias */
/* @design-tokens url('test_brand.json') format('style-dictionary3'); */

@custom-media --laptop (width >1200px) and (width <=1600px);

/* Base case, no aliasing */
@media (--laptop) {
  main {
    background: design-token('color.base.red.50');
  }
}

/*Aliasing as test_brand.json has a token definition in test_base.json*/
/* Uncomment this to demonstrate failed alias */
/* @media (--laptop) { */
/*   main { */
/*     background: design-token('color.brand.primary.base'); */
/*   } */
/* } */
```

test_base.json
```json
{
  "color": {
    "base": {
      "red": {
        "50": {
          "value": "#FFE5EE",
          "attributes": {
            "font": "base"
          }
        }
      }
    }
  }
}
```

test_brand.json
```json
{
  "color": {
    "brand": {
      "primary": {
        "base": {
          "value": "{color.base.red.50.value}"
        }
      }
    }
  }
}
```
