### ISSUE TITLE
[postcss-nesting] Nested mixins declaration order

### ISSUE THREAD

**Issue by pciarach** [csstools/postcss-plugins#1297]
### Bug description

Hello!

We have recently upgraded `postcss` and its plugins (including `postcss-nesting`) and noticed unexpected style orders in some places.
After some digging and debugging, it turned out that the differences come from `postcss-nesting` and nested `@mixin` rules interaction implemented in the `groupDeclarations` function.

Our previous assumption was that all styles from mixins would be placed exactly where the mixin was used. However, this behavior has been affected by the new grouping and reordering mechanism.

I’ve attempted to address this issue in the forked repo, but before submitting a pull request, I’d like to confirm whether this behavior is intentional or unintended. If it’s intentional, any hints/details will be welcome 😃 
Link to my changes: https://github.com/csstools/postcss-plugins/compare/main...pciarach:postcss-plugins:fix/nested-mixins-reorder

### Source CSS

```
@define-mixin mixinToOverride {
	display: flex;
}

@define-mixin mixinWithDecl {
	color: blue;
}

@define-mixin nestedMixins {
	@mixin mixinWithDecl;
	@mixin mixinToOverride;

	&:disabled {
		color: white;
	}
}

a {
	color: yellow;

	& b {
		@mixin nestedMixins;
		display: inline-flex;
	}
}

```

### Expected CSS

```
a {
	color: yellow;
}

a b {
	color: blue;
	display: flex;
	display: inline-flex;
}

a b:disabled {
	color: white;
}
```

### Actual CSS

```
a {
	color: yellow;
}

a b {
	color: blue;
	display: inline-flex;
	display: flex;
}

a b:disabled {
	color: white;
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Nesting

### Plugin version

12.0.3

### What OS are you experiencing this on?

Windows

### Node Version

20.11.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @pciarach,

I think you are right that this is a bug.
It's always fine to open a pull request by the way.

That makes it easy for us to pull the proposed changes locally and inspect them a bit more :)

**Comment by romainmenke** [comment]
I've tried to figure out what is going on.

Input CSS :

```css
a {
 	color: yellow;

 	& b {
 		@mixin nestedMixins;
 		display: inline-flex;
 	}
 }
```

Mixins :

`nestedMixins`

```css
@mixin mixinWithDecl;
@mixin mixinToOverride;

&:disabled {
  color: white;
}
```

`mixinWithDecl`

```css
color: blue;
```

`mixinToOverride`

```css
display: flex;
```

-------

If we fill in all the mixins first:

`first pass`

```css
a {
 	color: yellow;

 	& b {
 		@mixin mixinWithDecl;
 		@mixin mixinToOverride;

 		&:disabled {
 			color: white;
 		}

 		display: inline-flex;
 	}
 }
```

`second pass`

```css
a {
 	color: yellow;

 	& b {
 		color: blue;
 		display: flex;

 		&:disabled {
 			color: white;
 		}

 		display: inline-flex;
 	}
 }
```

Resolve nesting :

```css
a {
	color: yellow;
}

a b {
	color: blue;
	display: flex;
	display: inline-flex;
}

a b:disabled {
	color: white;
}
```

So from this perspective we expect `blue` before `white` and `flex` before `inline-flex`.

--------

If we resolve nesting first :

```css
a {
 	color: yellow;

 	& b {
 		@mixin nestedMixins;
 		display: inline-flex;
 	}
}
```

```css
a {
 	color: yellow;
}

a b {
 	@mixin nestedMixins;
 	display: inline-flex;
}
```

Nothing nested remains, but we can fill in mixins :

```css
a {
 	color: yellow;
}

a b {
 	@mixin mixinWithDecl;
 	@mixin mixinToOverride;

 	&:disabled {
 	 	color: white;
 	}

 	display: inline-flex;
}
```

Now can further resolve nesting :

```css
a {
 	color: yellow;
}

a b {
 	@mixin mixinWithDecl;
 	@mixin mixinToOverride;

 	display: inline-flex;
}

a b:disabled {
 	color: white;
}
```

More mixins :

```css
a {
	color: yellow;
}

a b {
	color: blue;
	display: flex;
	display: inline-flex;
}

a b:disabled {
	color: white;
}
```

So from this perspective we expect `blue` before `white` and `flex` before `inline-flex`.
That is the same as before.

So I think that either way there is a bug if the outcome doesn't match this manual transform.
