### ISSUE TITLE
Synchronous run of `postcss-custom-properties` leads to unexpected results

### ISSUE THREAD

**Issue by Antonio-Laguna** [csstools/postcss-plugins#132]
### Bug description

Introduced here: https://github.com/postcss/postcss-custom-properties/pull/181

Most of the time `canReturnSyncFunction` is `true` and this leads to vars in other places not being properly transformed, this is especially dangerous when combined with `postcss-import`.

### Source CSS

```css
/* util/an-import.css */
:root {
    --foo: red;
}
```

```css
/* Another file */
@import './util/an-import.css';

.foo {
    color: var(--foo);
}
```

### Expected CSS

```css
:root {
    --foo: red;
}

.foo {
    color: red;
    color: var(--foo);
}
```

### Actual CSS

```css
:root {
    --foo: red;
}

.foo {
    color: var(--foo);
}
```

### Extra config

This needs to happen on external files

### What plugin are you experiencing this issue on?

PostCSS Custom Properties

### Plugin version

12.0.2

### What OS are you experiencing this on?

macOS

### Node Version

14.17.3

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR
