### ISSUE TITLE
`postcss-light-dark-function` generates bloat css in `:root`

### ISSUE THREAD

**Issue by vovsemenv** [csstools/postcss-plugins#1454]
### What would you want to propose?

I try to use do this
```css
:root {
    --ad-other-focus: light-dark(var(--system-blue-200), var(--system-blue-300));
    --constant-bg-base-primary: light-dark(var(--gray-neutral-900), var(--constant-bg-base-primary-night));
}

```

but since i have 150+ colors
every light-dark produce new selector like this i end up in the selector hell. ( even chrome devTools stops working

```css
:root {
    --csstools-light-dark-toggle--0: var(--csstools-color-scheme--dark) var(--system-blue-200);
    --ad-other-focus: var(--csstools-light-dark-toggle--0, var(--system-blue-300));
    --csstools-light-dark-toggle--1: var(--csstools-color-scheme--dark) var(--gray-neutral-900);
    --constant-bg-base-primary: var(--csstools-light-dark-toggle--1, var(--constant-bg-base-primary-night));
}

:root {
    & * {
        --csstools-light-dark-toggle--1: var(--csstools-color-scheme--dark) var(--gray-neutral-900);
        --constant-bg-base-primary: var(--csstools-light-dark-toggle--1, var(--constant-bg-base-primary-night));
    }
}

:root {
    & * {
        --csstools-light-dark-toggle--0: var(--csstools-color-scheme--dark) var(--system-blue-200);
        --ad-other-focus: var(--csstools-light-dark-toggle--0, var(--system-blue-300));
    }
}
```

### Suggested solution

```css
// @postcss-light-dark-no-subselector
:root {
    --ad-other-focus: light-dark(var(--system-blue-200), var(--system-blue-300));
    --constant-bg-base-primary: light-dark(var(--gray-neutral-900), var(--constant-bg-base-primary-night));
}

```

that lead to this result without additional selectors

```css
:root {
    --csstools-light-dark-toggle--0: var(--csstools-color-scheme--dark) var(--system-blue-200);
    --ad-other-focus: var(--csstools-light-dark-toggle--0, var(--system-blue-300));
    --csstools-light-dark-toggle--1: var(--csstools-color-scheme--dark) var(--gray-neutral-900);
    --constant-bg-base-primary: var(--csstools-light-dark-toggle--1, var(--constant-bg-base-primary-night));
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @vovsemenv,

Thank you for reaching out about this.

Unfortunately there isn't much we can do about this.
The generated CSS is correct and the smallest/simplest it can be.

We test this extremely thoroughly and pass all the same tests that browsers do.

The `root * {}` blocks are needed because of how inheritance works with `light-dark()` and custom properties.

You can see this in action in this codepen: https://codepen.io/romainmenke/pen/wvLGwyb

Notice how the output for `light-dark()` is computed for each child element and not only once at the root.

-------

Maybe it is too soon to use `light-dark()` with so many colors and also in a setup where everything is a custom property?

Fallbacks/polyfills can never be as performant and efficient as native implementations.
Using a feature this intensive with a fallback/polyfill might not be ideal?

-------

> i end up in the selector hell

How do you mean?

These are all very low specificity selectors and shouldn't conflict with anything you wrote yourself.

Do you simply mean that there is a lot of generated CSS?


> even chrome devTools stops working

That seems like an issue with dev tools, not with `postcss-preset-env`?


-------

Is there an actual problem when rendering pages?
Or only a large CSS file and buggy chrome dev tools?

**Comment by romainmenke** [comment]
🤔 We can simplify one thing.

We can output a single `& * {}` rule per parent rule instead one per `light-dark()`.

```css
:root {
    & * {
        --csstools-light-dark-toggle--1: var(--csstools-color-scheme--dark) var(--gray-neutral-900);
        --constant-bg-base-primary: var(--csstools-light-dark-toggle--1, var(--constant-bg-base-primary-night));
    }
}

:root {
    & * {
        --csstools-light-dark-toggle--0: var(--csstools-color-scheme--dark) var(--system-blue-200);
        --ad-other-focus: var(--csstools-light-dark-toggle--0, var(--system-blue-300));
    }
}
```

->

```css
:root {
    & * {
        --csstools-light-dark-toggle--1: var(--csstools-color-scheme--dark) var(--gray-neutral-900);
        --constant-bg-base-primary: var(--csstools-light-dark-toggle--1, var(--constant-bg-base-primary-night));
        --csstools-light-dark-toggle--0: var(--csstools-color-scheme--dark) var(--system-blue-200);
        --ad-other-focus: var(--csstools-light-dark-toggle--0, var(--system-blue-300));
    }
}
```
