### ISSUE TITLE
postcss-custom-media: incorrect rendering with nested rules

### ISSUE THREAD

**Issue by massimo-cassandro** [csstools/postcss-plugins#1519]
### Bug description

In custom media queries inside nested rules, the parent selectors are ignored

### Source CSS

```css
.some-class {

  .nested {
    flex-direction: column;

    @media (--my-custom-media) {
      flex-direction: row;
    }
  }
}
```

### Expected CSS

```css
.some-class {
  .nested {
    flex-direction: column;
  }
}
@media (min-width: 480px) { /* --my-custom-media */
  .some-class {
    .nested {
      flex-direction: row;
    }
  }
}
```

### Actual CSS

```css
.some-class {
  .nested {
    flex-direction: column;
  }
}
@media (min-width: 480px) { /* --my-custom-media */
  .nested {
    flex-direction: row;
  }
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

PostCSS Custom Media Queries

### Plugin version

11.0.5

### What OS are you experiencing this on?

macOS

### Node Version

22.3.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTQwY3VzdG9tLW1lZGlhJTIwLS1teS1jdXN0b20tbWVkaWElMjAobWluLXdpZHRoJTNBJTIwNDgwcHgpJTNCJTVDbiU1Q24uc29tZS1jbGFzcyUyMCU3QiU1Q24lNUNuJTIwJTIwLm5lc3RlZCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBmbGV4LWRpcmVjdGlvbiUzQSUyMGNvbHVtbiUzQiU1Q24lNUNuJTIwJTIwJTIwJTIwJTQwbWVkaWElMjAoLS1teS1jdXN0b20tbWVkaWEpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGZsZXgtZGlyZWN0aW9uJTNBJTIwcm93JTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlN0QlNUNuJTdEJTIyJTJDJTIyY29uZmlnJTIyJTNBJTdCJTIyYnJvd3NlcnMlMjIlM0ElNUIlMjIlM0UlMjAwLjIlMjUlMjBhbmQlMjBub3QlMjBkZWFkJTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTAlMkMlMjJzdGFnZSUyMiUzQTIlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCU3RCU3RA==

With latest PostCSS Preset Env you get: 

```css
.some-class .nested {
  flex-direction: column;
}

@media (min-width: 480px) {
  .some-class .nested {
    flex-direction: row;
  }
}
```

This seems correct.

----

Can you provide a complete reproduction that shows that the issue is with `postcss-custom-media` or `postcss-nesting`?
