### ISSUE TITLE
PostCSS Initial : unexpected behaviour for `preserve` option.

### ISSUE THREAD

**Issue by rubycon** [csstools/postcss-plugins#1564]
### Bug description

Running PostCSS initial with `preserve: false` on :
```css
{
  opacity: 1;
  pointer-events: initial;
}
```
will result in 
```css
{
  opacity: 1;
}
```
The issue is that `pointer-events` IS NOT amongst the properties handled by the plugin and `initial` is a perfectly valid value. Wouldn't the expected behaviour be that the prop is preserved as a fallback *if a replacement is found*, as it was the case with the [original plugin](https://github.com/maximkoretskiy/postcss-initial) `replace` option. With the current behaviour all properties not handled by the plugin with value `initial` are simply stripped!

### Source CSS

```css
{
  opacity: 1;
  pointer-events: initial;
}
```

### Expected CSS

```css
{
  opacity: 1;
  pointer-events: initial;
}
```

### Actual CSS

```css
{
  opacity: 1;
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### Debug output

PostCSS Initial is not available in `@csstools/csstools-cli`.

### What plugin are you experiencing this issue on?

PostCSS Initial

### Plugin version

2.0.0

### What OS are you experiencing this on?

macOS

### Node Version

20

### Validations

- [x] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
