### ISSUE TITLE
Not removing unnecessary `:is()` in selector `.main > :is(.wrapper > *, .wrapper2 > *)`

### ISSUE THREAD

**Issue by n0099** [csstools/postcss-plugins#1625]
### Bug description

As title.

### Source CSS

```css
.main > :is(.wrapper > *, .wrapper2 > *) {
    font-size: 2rem;
}
```

### Expected CSS

```css
.main > .wrapper > * {
    font-size: 2rem;
}
.main > .wrapper2 > * {
    font-size: 2rem;
}
```

### Actual CSS

```css
.main > :is(.wrapper > *) {
    font-size: 2rem;
}
.main > :is(.wrapper2 > *) {
    font-size: 2rem;
}
```

### Playgound example

https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyLm1haW4lMjAlM0UlMjAlM0Fpcygud3JhcHBlciUyMCUzRSUyMColMkMlMjAud3JhcHBlcjIlMjAlM0UlMjAqKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBmb250LXNpemUlM0ElMjAycmVtJTNCJTVDbiU3RCUyMiUyQyUyMmNvbmZpZyUyMiUzQSU3QiUyMmJyb3dzZXJzJTIyJTNBJTVCJTIyZGVmYXVsdHMlMjIlNUQlMkMlMjJtaW5pbXVtVmVuZG9ySW1wbGVtZW50YXRpb25zJTIyJTNBMSUyQyUyMnN0YWdlJTIyJTNBMiUyQyUyMmxvZ2ljYWwlMjIlM0ElN0IlMjJpbmxpbmVEaXJlY3Rpb24lMjIlM0ElMjJsZWZ0LXRvLXJpZ2h0JTIyJTJDJTIyYmxvY2tEaXJlY3Rpb24lMjIlM0ElMjJ0b3AtdG8tYm90dG9tJTIyJTdEJTdEJTdE

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### Debug output

```
postcss-is-pseudo-class: test.css:1:1: Complex selectors in '.main > :is(.wrapper > *, .wrapper2 > *)' can not be transformed to an equivalent selector without ':is()'.
postcss-is-pseudo-class: test.css:1:1: Complex selectors in '.main > :is(.wrapper > *)' can not be transformed to an equivalent selector without ':is()'.
postcss-is-pseudo-class: test.css:1:1: Complex selectors in '.main > :is(.wrapper2 > *)' can not be transformed to an equivalent selector without ':is()'.
```

### `postcss-preset-env`
```js
{
  minimumVendorImplementations: 2
}
```
### browserslist
```browserslist
defaults
> 0.1% in CN
fully supports es6-module and fully supports url
```

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

10.2.1

### What OS are you experiencing this on?

Linux, Windows

### Node Version

24.1.0

### Validations

- [x] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
