### ISSUE TITLE
[postcss-nesting] Unexpected output with postcss-inherit usage

### ISSUE THREAD

**Issue by AlecRust** [csstools/postcss-plugins#209]
### Bug description

When I use `postcss-nesting` instead of `postcss-nested`, my previous usage of `@inherit` provided by `postcss-inherit` breaks.

### Source CSS

```css
.u-hiddenVisually {
  border: 0 !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}

/* then later in a different file: */

.FormField--hiddenLabel {

  & .FormField-label {

    @inherit: .u-hiddenVisually;
  }
}
```

### Expected CSS

```css
.u-hiddenVisually,
.FormField--hiddenLabel .FormField-label {
  border: 0 !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}
```

### Actual CSS

```css
.u-hiddenVisually,
& .FormField-label {
  border: 0 !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}
```

### What plugin are you experiencing this issue on?

PostCSS Nesting

### Plugin version

5.0.6

### Node Version

16.13.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
