### ISSUE TITLE
No warning on missed `%` in `lch(0 0 0 / 0)`

### ISSUE THREAD

**Issue by ai** [csstools/postcss-plugins#240]
### Bug description

`postcss-lab-function` ignores `lch(0 0 0 / 0)` (without `%` for L).

I am not sure that it is valid syntax. But even if it is not valid, the result could confuse users.

### Source CSS

```css
body {
  background: lch(0 0 0 / 0);
}
```

### Expected CSS

If it is valid syntax:

```css
body {
  background: rgba(0, 0, 0, 0)
}
```

And warning if it is not valid (maybe CSS syntax error with an option to switch to warning).

### Actual CSS

```css
body {
  background: lch(0 0 0 / 0);
}
```

### What plugin are you experiencing this issue on?

PostCSS Lab Function

### Plugin version

4.0.4

### What OS are you experiencing this on?

Linux

### Node Version

17.4.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
