### ISSUE TITLE
Nesting plugin generates duplicate class

### ISSUE THREAD

**Issue by enyo** [csstools/postcss-plugins#261]
### Bug description

I have the nesting plugin enabled:

```
// postcss.config.cjs
const config = {
  plugins: [
    postcssNesting(),
    // etc.....
```

When I compile the CSS for a svelte component, the CSS is correct and looks like this:

```css
button.s-5xw9RGpuDz7F {
 width:100%
}
```

But as soon as I add a nested style, this is what I get:

```css
button.s-5xw9RGpuDz7F.s-5xw9RGpuDz7F {
 width:100%
}
button.s-5xw9RGpuDz7F .s-5xw9RGpuDz7F:hover {
 color:red
}
```

As you can see, the class for the button has been duplicated, and with the `:hover` it broke the selector.

### Source CSS

```css
  button {
    width: 100%;
    & :hover {
      color: red;
    }
  }
```

### Expected CSS

```css
button.s-5xw9RGpuDz7F {
 width:100%
}
button.s-5xw9RGpuDz7F:hover {
 color:red
}
```

### Actual CSS

```css
button.s-5xw9RGpuDz7F.s-5xw9RGpuDz7F {
 width:100%
}
button.s-5xw9RGpuDz7F .s-5xw9RGpuDz7F:hover {
 color:red
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

No

### Extra config

It's happening in a svelte kit app.

### What plugin are you experiencing this issue on?

PostCSS Nesting

### Plugin version

10.1.2

### What OS are you experiencing this on?

macOS

### Node Version

17.4.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by enyo** [comment]
I'm an idiot. Disregard. The syntax is `&:hover` of course, not, `& :hover`

**Comment by jonathantneal** [comment]
You are awesome, @enyo. You are learning a thing, you encountered an issue, and you took time to explain it and share it. Then you learned more. ❤️

**Comment by romainmenke** [comment]
@enyo There does seem to be an interop issue here.

```pcss
button {
  width: 100%;
  & :hover {
    color: red;
  }
}
```

With the CLI :

`pbpaste | npx @csstools/csstools-cli postcss-nesting --no-map `

Becomes :

```css
button {
  width: 100%
}
button :hover {
  color: red;
}
```

Your actual :

```css
button.s-5xw9RGpuDz7F.s-5xw9RGpuDz7F {
 width:100%
}
button.s-5xw9RGpuDz7F .s-5xw9RGpuDz7F:hover {
 color:red
}
```


This bits seems weird : `button.s-5xw9RGpuDz7F .s-5xw9RGpuDz7F:hover`
Is it normal and expected for `.s-5xw9RGpuDz7F` to appear twice here?

I would only expect it once, but I don't know the tooling you are also using.

`& :hover` is totally valid and should work even it was not what you intended at the moment.

Can you give a bit more details?
Especially other PostCSS plugins and the order in which they are used can be helpful.

Thank you for bringing this up!
