### ISSUE TITLE
Invalid syntax after upgrading to postcss-preset-env@7.4.1

### ISSUE THREAD

**Issue by IonicaBizau** [csstools/postcss-plugins#275]
I am trying to upgrade `postcss-preset-env` from `6.7.0` to the latest version. However, I have the following problem:

```css
strong {
    & span {
        color: #fff;
    }
}
```

The code above is compiled correclty via 6.7.0:

```css
strong span{color:#fff}
```

After upgrading to 7.4.1, I am getting a syntax error/warning:

```
Unexpected '}' at 13:0.
Invalid property name '& span {
        color' at 10:4. Ignoring.
Invalid selector '}
```

Any ideas why is this happening?

**Comment by romainmenke** [comment]
Thank you for reporting this!

This example does work for me :/

`echo "strong { & span { color: #fff; } }" | npx @csstools/csstools-cli postcss-preset-env --no-map -p '{ "stage": 0 }'`

Outputs : 

```css
strong span { color: #fff; }
```

Can you share a bit more about you setup?
Other plugins and your postcss config?
