### ISSUE TITLE
[postcss-preset-env] Where CSS variables are used, duplicate styles are generated 

### ISSUE THREAD

**Issue by wanweiwang2012** [csstools/postcss-plugins#290]
### Bug description

where CSS variables are used, duplicate styles are generated, the output is normal when the postcss-preset-env is not used.

### Source CSS

```css
:root {
  --font-size: 16px;
  --font-line-height: 1.5;
  --font-family: Avenir, Helvetica, Arial, sans-serif;
  --min-width: 1200px;
  --text-primary: #15141a;
  --background-primary: #fff;
  --border-primary: #ebebeb;
}
```

```css
body {
  min-width: var(--min-width);
  color: var(--text-primary);
  background-color: var(--background-primary);
  overflow-x: auto;
  font-size: var(--font-size);
  line-height: var(--font-line-height);
  font-family: var(--font-family);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transition: color 0.3s ease, background-color 0.3s ease;
}
```

### Expected CSS

```css
body {
  min-width: var(--min-width);
  color: var(--text-primary);
  background-color: var(--background-primary);
  overflow-x: auto;
  font-size: var(--font-size);
  line-height: var(--font-line-height);
  font-family: var(--font-family);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transition: color 0.3s ease, background-color 0.3s ease;
}
```

### Actual CSS

```css
body {
    min-width: 1200px;
    min-width: var(--min-width);
    color: #15141a;
    color: var(--text-primary);
    background-color: #fff;
    background-color: var(--background-primary);
    overflow-x: auto;
    font-size: 16px;
    font-size: var(--font-size);
    line-height: 1.5;
    line-height: var(--font-line-height);
    font-family: Avenir, Helvetica, Arial, sans-serif;
    font-family: var(--font-family);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    transition: color 0.3s ease, background-color 0.3s ease;
}
```

### Extra config

```js
postcss: {
    plugins: [
      postcssPresetEnv({
        stage: 2,
        features: {
          "nesting-rules": true,
        },
      }),
    ],
  },
```

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

^7.4.2

### What OS are you experiencing this on?

macOS

### Node Version

v12.14.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
@wanweiwang2012 I might be missing the issue, but I think this is actually a feature.

```css
:root {
  --min-width: 1200px;
}

body {
  min-width: var(--min-width);
}
```

becomes :

```css
body {
  min-width: 1200px;
  min-width: var(--min-width);
}
```

Any browser that doesn't support `var(--min-width)` would get the fallback of `1200px`.

This is what `postcss-preset-env` does.
It transforms your source CSS to something more browsers can handle.

Is there anything in particular that is breaking because of this?
