### ISSUE TITLE
`:has()` with selector having colon inside

### ISSUE THREAD

**Issue by sntran** [csstools/postcss-plugins#320]
### Bug description

When trying to use `css-has-pseudo` plugin in a Tailwind project, the browser script throws an exception when parsing a selector with colon inside, which is quite popular in Tailwind.

For example, with the following source CSS, after running through the PostCSS plugin:

```css
.has-peer\:bg-black[\:has\(\%2B\.peer\)] {
    --tw-bg-opacity: 1;
    background-color: rgb(0 0 0/var(--tw-bg-opacity))
}

.has-peer\:bg-black:has(+.peer) {
    --tw-bg-opacity: 1;
    background-color: rgb(0 0 0/var(--tw-bg-opacity))
}
```

### Actual Behavior

Browser script throws an error:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '.has-peer:bg-black' is not a valid selector.
```

### Expected Behavior

Browser script should parse the CSS and polyfills it correctly.

I traced it down to [this line](https://github.com/csstools/postcss-plugins/blob/b1a0d9ee76e0f14579515ce9cef9e2675482e3a3/plugins/css-has-pseudo/src/browser.js#L108), specifically the `e.selectorText.replace(/\\(.)/g, "$1")`.  That would strips the escape `\` before the colon, resulting in `.has-peer:bg-black`, which is an invalid selector for `document.querySelectorAll`.

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

CSS Has Pseudo

### Plugin version

3.0.4

### What OS are you experiencing this on?

macOS

### Node Version

16.13.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
