### ISSUE TITLE
postcss-logical not transforming `scroll-padding-block-start`

### ISSUE THREAD

**Issue by lukaskoeller** [csstools/postcss-plugins#326]
### Bug description

The property `scroll-padding-block-start` is not transformed by `postcss-logical` plugin.

I also could verify this in the `postcss-preset-env` [playground](https://preset-env.cssdb.org/playground/).

### Source CSS

```css
html {
  scroll-padding-block-start: 24px;
  padding-block: 12px;
}
```

### Expected CSS

```css
html {
  scroll-padding-top: 24px;
  padding-top: 12px;
  padding-bottom: 12px;
}
```

### Actual CSS

```css
html {
  scroll-padding-block-start: 24px;
  padding-top: 12px;
  padding-bottom: 12px;
}
```

### Debug output

It is about `postcss-preset-env`, though can't see any debug option

### What plugin are you experiencing this issue on?

PostCSS Preset Env, PostCSS Logical

### Plugin version

7.4.1

### What OS are you experiencing this on?

macOS

### Node Version

14.18.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
