### ISSUE TITLE
Add the alias `dt()` to `design-token()` function

### ISSUE THREAD

**Issue by shaal** [csstools/postcss-plugins#406]
### What would you want to propose?

As a developer using `design-token()` functions, I would like to add the alias `dt()`, so that CSS files are more concise and readable

### Suggested solution

```css
.foo {
    color: dt('color.background.primary');
}
```
Is the same as
```css
.bar {
    color: design-token('color.background.primary');
}
```

### Additional context

A project that uses design tokens would have CSS files full of the repeating function `design-token()`
I believe that using `dt()` as alias, would result in increased readability of these files.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR
