### ISSUE TITLE
Selector starting with numeral transpiles incorrectly

### ISSUE THREAD

**Issue by nekitk** [csstools/postcss-plugins#413]
```css
@custom-selector :--3xl .3xl;

:--3xl {
  font-size: 46px;
}
```

Expected result:
```css
.3xl {
  font-size: 46px;
}
```

Actual result:
```css
@custom-selector :--3xl .3xl;

class=css-var>:--3xl {
  font-size: 46px;
}
```

[Codepen](https://codepen.io/nekitk/pen/rNVOXLv)
