### ISSUE TITLE
Compound query produces invalid syntax

### ISSUE THREAD

**Issue by nickstanish** [csstools/postcss-plugins#415]
Getting an incorrect expansion when custom media queries are combined

```css
@custom-media --screen only screen;
@custom-media --md-and-larger1 --screen and (width >= 570px);
@custom-media --md-and-larger2 (--screen) and (width >= 570px);
@custom-media --md-and-larger3 only screen and (width >= 570px);

@media (--md-and-larger1) {
  body {
    background-color: red;
  }
}
@media (--md-and-larger2) {
  body {
    background-color: yellow;
  }
}
@media (--md-and-larger3) {
  body {
    background-color: green;
  }
}
```

Actual Output vs Expected Output:

```diff
- @media only screen(min-width: 570px) {
+ @media only screen and (min-width: 570px) {
  body {
    background-color: red;
  }
}
- @media only screen(min-width: 570px) {
+ @media only screen and (min-width: 570px) {
  body {
    background-color: yellow;
  }
}
@media only screen and (min-width: 570px) {
  body {
    background-color: green;
  }
}
```
