### ISSUE TITLE
can make multiple custom-media work together?

### ISSUE THREAD

**Issue by tx0c** [csstools/postcss-plugins#422]
I have multiple custom-media defined, some for height and some for widths,

```css
@custom-media --md-up (min-width: 1024px);
...
@custom-media --h-md-up (min-height: 800px);
```

and each have individual use cases, and there are corner cases I want to apply

```css
@media (--md-up) and (--h-md-up) {       // but this does not work
  ...
}
```

then I tried:
```css
@media (--md-up) and (min-height: 800px) {       // this works
  ...
}
```

then I think this would probably work, but this would lead to too many combinations not very flexible;
```css
@custom-media --wh-md-up (min-width: 1024px) and (min-height: 800px);
```

so, can make this work?
```
@media (--md-up) and (--h-md-up) {
```

**Comment by romainmenke** [comment]
@tx0c 

We just released a new version (v8.0.1) and we think it now works correctly :

```css
@custom-media --md-up (min-width: 1024px);
@custom-media --h-md-up (min-height: 800px);


@media (--md-up) and (--h-md-up) {
	.foo {
		order: 1000;
	}
}
```

becomes :

```css
@media (min-width: 1024px) and (min-height: 800px) {
	.foo {
		order: 1000;
	}
}
```

Can you confirm if it is fixed for you?
