### ISSUE TITLE
Not working with complex nesting (@nest)

### ISSUE THREAD

**Issue by smth** [csstools/postcss-plugins#424]
When used in combination with `postcss-nesting`, custom selectors using `@nest` do not get properly transpiled.

```css
@custom-selector :--parent
  @nest .parent &;

.child {
  :--parent {
    /* styles */
  }
}
```

Results in

```css 
.child {
  @nest .parent & {
    /* styles */
  }
}
```

Instead of the expected

```css
.parent .child {
  /* styles */
}
```
