### ISSUE TITLE
custom selector and custom media do not play nice with cascade layers

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#481]
I think this behaviour is largely undefined at the moment but declaring custom selectors and custom media inside `@layer` does not work.

Should it work?

**Comment by Antonio-Laguna** [comment]
wow, that's a big question. I'm not sure. On one hand it's like, nope, shouldn't work and the other hand is a big _mayybeee?_

**Comment by romainmenke** [comment]
> mayybeee

Hehe, after typing this up I kept coming back to that :D

--------

I think in theory they could work, but them being nested in `@layer` just doesn't have any effect.

It will be safest if we keep the current (broken) behaviour and wait until the relevant specs are updated.

------

Forgot to mention that I encountered this with imported styles where it is a bit more unexpected.

```css
/* file-alpha.css */

**Comment by mirisuzanne** [comment]
I'm pretty sure we did [spec this](https://drafts.csswg.org/css-cascade-5/#layering) - but in a short mention nested between examples:

> Name-defining at-rules such as `@keyframes` or `@font-face` that are defined inside cascade layers also use the layer order when resolving name collisions.

I think that would apply to any sort of custom-property/selector/media at-rules, which are generally name-defining. So that means they should:

1. Work as expected even inside `@layer`
2. If there are name conflicts, the higher layer should win (this can be achieved by ordering them, I think?)

**Comment by romainmenke** [comment]
Thank you @mirisuzanne for finding this issue and sharing this.

I've been working on an updated version which ensures this works as you describe : https://github.com/csstools/postcss-plugins/pull/543

The main issue was that the plugins that handle custom selectors and custom media transformed the CSS before the cascade layers plugin.

This is part of the upcoming major release of `postcss-preset-env` where we hope to align everything much more closely with the CSS specifications.

------

_I got side-tracked a bit recently taking on maintenance for the `polyfill-library` and 9to5 work. Hopefully more time will be available soon!_

**Comment by romainmenke** [comment]
1. we want to ship v8 with a version of nesting that will land in browsers, we don't want to ship v9 a short time after only because of nesting
2. we want to have solved `@media` param parsing
3. we want to have an implementation of logical properties that is much simpler and more correct at the same time.

I am currently working on 1 and 2.
I would not count on v8 being ready within the next few weeks :)

**Comment by romainmenke** [comment]
This is resolved in the latest pre-release version of `postcss-preset-env` : https://github.com/csstools/postcss-plugins/blob/postcss-preset-env--v8/plugin-packs/postcss-preset-env/CHANGELOG.md#800-alpha1-november-14-2022

**Comment by wesleyboar** [comment]
I want this fix, but also use `postcss-env-function`. That pre-release also says "Removed `postcss-env-function` (breaking)." So:

1. Does this mean that if I want this fix via `postcss-preset-env`, I need to abandon `postcss-env-function`?
2. If so, should I be able to install `postcss-custom-selectors@7.0.0` atop my setup (that relies on `postcss-env-function`) without breaking something?

**Comment by Antonio-Laguna** [comment]
@wesleyboar thanks for reaching out!

1. Yes, and no.
2. You'll get an error because of mismatched dependencies which you can choose to ignore but we won't be supporting such environment so errors could happen.

Clarifying on answer to 1, you should be able to install postcss-env-function separately as it will stay frozen. We wont' be releasing new fixes for that plugin nor relying on it but you still should be able to use it either as part of your stack of PostCSS plugins or even use `insertBefore`/`insertAfter` (see [docs](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#insertbefore--insertafter)) with PostCSS Preset Env to inject it there.

**Comment by wesleyboar** [comment]
My 2:20 morning brain could not think to install `postcss-env-function` separately. Thank you 😅.

I tried installing the beta and `postcss-env-function`. I do not see the fix succeed.

Has my 3:20 morning brain I done anything wrong?

### Source & Config

<details><summary><code>package.json</code> (abbreviated)</summary>

```json
  "peerDependencies": {
    "commander": "^9.4.1",
    "cssnano": "^5.1.14",
    "js-yaml": "^4.1.0",
    "merge-lite": "^1.0.2",
    "node-cmd": "^5.0.0",
    "npm-watch": "^0.11.0",
    "postcss": "^8.4.18",
    "postcss-banner": "^4.0.1",
    "postcss-cli": "^10.0.0",
    "postcss-extend": "^1.0.5",
    "postcss-env-function": "4.0.6",
    "postcss-import": "^15.0.0",
    "postcss-preset-env": "^8.0.0-alpha.1",
    "postcss-replace": "^2.0.0"
  },
  "devDependencies": {
    "@frctl/fractal": "^1.5.13",
    "@frctl/mandelbrot": "^1.10.1"
  },
```

No `dependencies`. Long story. Temporary. Does it matter?

</details>

<details><summary><code>npm list</code></summary>

```bash
➜  Core-Styles git:(dev--task/form-patterns--task/base-cms-portal-header) ✗ npm list postcss-env-function
@tacc/core-styles@v0.11.0-30-g66400cb /Users/wbomar/Code/Core-Styles
└── postcss-env-function@4.0.6

➜  Core-Styles git:(dev--task/form-patterns--task/base-cms-portal-header) ✗ npm list postcss-custom-selectors           
@tacc/core-styles@v0.11.0-30-g66400cb /Users/wbomar/Code/Core-Styles
└─┬ postcss-preset-env@8.0.0-alpha.1
  └── postcss-custom-selectors@7.0.0
```

</details>

<details><summary><code>src/.postcssrc.yml</code></summary>

```yaml
plugins:
  postcss-import:
    path:
      - src/lib
  postcss-extend: {}
  postcss-env-function:
    importFrom:
      - src/lib/_themes/default.json
  postcss-preset-env:
    stage: false
    features:
      custom-media-queries: true
      media-query-ranges: true
      custom-selectors: true
  cssnano:
    preset:
      - default
      - discardDuplicates:
          exclude: true
        mergeRules:
          exclude: true
  postcss-banner:
    banner: '@tacc/core-styles v0.11.0-30-g66400cb+ | MIT | github.com/TACC/Core-Styles'
    inline: true
    important: true
  postcss-replace:
    pattern: ../../fonts/
    data:
      replaceAll: fonts/
```

</details>

<details><summary><code>src/.../c-button.css</code></summary>

```postcss
@custom-selector :--disabled :disabled,[disabled];

.c-button {
  display: inline-block;

  box-sizing: border-box;

  border-width: var(--global-border-width--normal);
  border-style: solid;
}

.c-button:not(:--disabled) {
  cursor: pointer; /* WARNING: Opinionated */
}
```

</details>

### No `@import`

✓ The @custom-selector` is parsed away.

<details><summary><code>dist/c-button.css</code></summary>

```css
/*! @tacc/core-styles v0.11.0-30-g66400cb+ | MIT | github.com/TACC/Core-Styles */.c-button{border-style:solid;border-width:var(--global-border-width--normal);box-sizing:border-box;display:inline-block}.c-button:not(:is(:disabled,[disabled])){cursor:pointer}
```

</details>

### Use `@import`

ⓧ The @custom-selector` remains.

<details><summary><code>src/.../core-styles.base.css</code></summary>

```postcss
/*! core-styles.base.css */
@import url("./components/c-button.css") layer(components);
```

</details>

<details><summary><code>dist/core-styles.base.css</code></summary>

```css
/*! @tacc/core-styles v0.11.0-30-g66400cb+ | MIT | github.com/TACC/Core-Styles */
/*! core-styles.base.css */@layer components{@custom-selector :--disabled :disabled,[disabled];.c-button{border-style:solid;border-width:var(--global-border-width--normal);box-sizing:border-box;display:inline-block}.c-button:not(:--disabled){cursor:pointer}}
```

</details>
