### ISSUE TITLE
[preset-env] unexpected whitespace with postcss-custom-media

### ISSUE THREAD

**Issue by carlosjeurissen** [csstools/postcss-plugins#491]
### Bug description

postcss-custom-media adds whitespace at the top.

### Source CSS

```css
/* postcss-custom-media */
@custom-media --small-viewport (max-width: 30em);

@media (--small-viewport) {
  .postcss-custom-media-test {
    color: red;
  }
}
```

### Expected CSS

```css
/* postcss-custom-media */
@media (max-width: 30em) {
  .postcss-custom-media-test {
    color: red;
  }
}
```

### Actual CSS

```css
/* postcss-custom-media */

@media (max-width: 30em) {
  .postcss-custom-media-test {
    color: red;
  }
}
```

### What plugin are you experiencing this issue on?

PostCSS Custom Media Queries

### Plugin version

8.0.2

### Node Version

18.4.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
