### ISSUE TITLE
not support css vars in local scope?

### ISSUE THREAD

**Issue by memory-lovers** [csstools/postcss-plugins#542]
### Bug description

I want to expand css vars.
I tried to use `postcss-custom-properties`, but some variables were not expanded..

`postcss-custom-properties` does not support vars in local scope?

### Source CSS

```css
:root {
  --bg-opacity: 1;
}

.text-white {
  --text-opacity: 1;
  color: rgba(255, 255, 255, var(--text-opacity));
}
.bg-black {
  --bg-opacity: 0.4;
  background-color: rgba(0, 0, 0, var(--bg-opacity));
}
```

### Expected CSS

```css
.text-white {
  color: rgba(255, 255, 255, 1);
}
.bg-black {
  background-color: rgba(0, 0, 0, 0.4);
}
```

### Actual CSS

```css
.text-white {
  --text-opacity: 1;
  color: rgba(255, 255, 255, var(--text-opacity));
}
.bg-black {
  --bg-opacity: 0.4;
  background-color: rgba(0, 0, 0, 1);
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### Extra config

i used below script.

```typescript
// main.ts
import postcss from "postcss";
import customProperties from "postcss-custom-properties";

async function main() {
  const inputCss = `
:root {
  --bg-opacity: 1;
}

.text-white {
  --text-opacity: 1;
  color: rgba(255, 255, 255, var(--text-opacity));
}
.bg-black {
  --bg-opacity: 0.4;
  background-color: rgba(0, 0, 0, var(--bg-opacity));
}
`;

  const { css } = await postcss([
    customProperties({ preserve: false }),
  ]).process(inputCss, { from: "sample.css" });

  console.log(css);
}

main().then((_) => process.exit());
```

output is ...

```shell
$ node --loader ts-node/esm main.ts
.text-white {
  --text-opacity: 1;
  color: rgba(255, 255, 255, var(--text-opacity));
}
.bg-black {
  --bg-opacity: 0.4;
  background-color: rgba(0, 0, 0, 1);
}
```

My Environment is ...

- postcss: 8.4.14
- postcss-custom-properties: 12.1.8
- node: v16.13.2
- ts-node: 10.8.2
- typescript: 4.7.4
- MacOS

### What plugin are you experiencing this issue on?

PostCSS Custom Properties

### Plugin version

12.1.8

### What OS are you experiencing this on?

macOS

### Node Version

16.13.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @memory-lovers thank you for reporting this!

This is a bit of a complex issue :)

```css
:root {
  --something: 1;
}
```

Here we now that `:root` will always exist in the document so we also now that `--something: 1;` will be applied.

We also now that any element will be a child of `:root` so they will all inherit `--somthing: 1;`.

This makes the value safe to use as a fallback.

--------

```css
.a-thing {
  --something: 1;
}
```

We can not use this as it is only applied if your document also has something with `class="a-thing"`.

There are some simpler cases like your example were we can be reasonably sure that this would just work :

```css
.text-white {
  --text-opacity: 1;
  color: rgba(255, 255, 255, var(--text-opacity));
}

/* becomes */

.text-white {
  --text-opacity: 1;
  color: rgba(255, 255, 255, 1);
}
```

But this would be incorrect if you also had :

```css
.text-white--semi-transparent {
  --text-opacity: 0.8;
}
```

We can not determine that `.text-white` and `.text-white--semi-transparent` will be set on the same element : `<span class="text-white text-white--semi-transparent"`

--------

Because "scoped" CSS variables are so complex this plugin does not transform them.
But support in browsers for CSS variables is really good now.

So you can set `preserve: true;` instead of `preserve: false;`

Which gives you :

```css
:root {
	--bg-opacity: 1;
}

.text-white {
	--text-opacity: 1;
	color: rgba(255, 255, 255, var(--text-opacity));
}
.bg-black {
	--bg-opacity: 0.4;
	background-color: rgba(0, 0, 0, 1);
	background-color: rgba(0, 0, 0, var(--bg-opacity));
}
```

This does not help you with `--text-opacity`.
But you can provide a default value for each CSS var to resolve this last issue :


```css
:root {
	--bg-opacity: 1;
	--text-opacity: 0.8; /* default */
}

.text-white {
	--text-opacity: 1;
	color: rgba(255, 255, 255, var(--text-opacity));
}
.bg-black {
	--bg-opacity: 0.4;
	background-color: rgba(0, 0, 0, var(--bg-opacity));
}
```

becomes ->

```css
:root {
	--bg-opacity: 1;
	--text-opacity: 0.8; /* default */
}

.text-white {
	--text-opacity: 1;
	color: rgba(255, 255, 255, 0.8);
	color: rgba(255, 255, 255, var(--text-opacity));
}
.bg-black {
	--bg-opacity: 0.4;
	background-color: rgba(0, 0, 0, 1);
	background-color: rgba(0, 0, 0, var(--bg-opacity));
}
```

This will make your site work with default values in very old browsers like Internet Explorer, while keeping them visually accurate in modern browsers.
