### ISSUE TITLE
[postcss-custom-properties] issue when used with postcss-html (document node)

### ISSUE THREAD

**Issue by lubomirblazekcz** [csstools/postcss-plugins#595]
### Bug description

Custom properties are not transformed correctly with `postcss-html`, this might be problem with document node support as mentioned in https://github.com/ota-meshi/postcss-html/issues/68

### Source CSS

```css
 :root {
    --blue: blue
  }
  
  body td {
      color: var(--blue)
  }
  
  @media all and (max-width: 600px) {
      body {
          color: red;
      }
  }
```

### Expected CSS

```css
:root {
    --blue: blue
  }
  
  body td {
      color: blue
  ;
      color: var(--blue)
  }
  
  @media all and (max-width: 600px) {
      body {
          color: red;
      }
  }
```

### Actual CSS

```css
 :root {
    --blue: blue
  }
  
  body td {
      color: var(--blue)
  }
  
  @media all and (max-width: 600px) {
      body {
          color: red;
      }
  }
```

### What plugin are you experiencing this issue on?

PostCSS Custom Properties

### Plugin version

12.1.8

### What OS are you experiencing this on?

macOS

### Node Version

18.6.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@lubomirblazekcz Can you provide a full reproduction?

The CSS on its own works fine : 

```css
 :root {
    --blue: blue
  }
  
  body td {
      color: var(--blue)
  }
  
  @media all and (max-width: 600px) {
      body {
          color: red;
      }
  }
```

becomes :

```css
 :root {
    --blue: blue
  }
  
  body td {
      color: blue
  ;
      color: var(--blue)
  }
  
  @media all and (max-width: 600px) {
      body {
          color: red;
      }
  }
```

**Comment by lubomirblazekcz** [comment]
It's mentioned in https://github.com/ota-meshi/postcss-html/issues/68, with that html you get the non-working result. 

@ota-meshi mentioned that it's actually a problem with document nodes, which postcss-custom-properties might not support. I don't know if that is something that can be fixed though.

**Comment by romainmenke** [comment]
I have no idea how to add support for document nodes (or what they are) :/
I will need to look into that.

------------------

A quick check does reveal that `Once` is called two times.
This is unexpected as the example in the other issue only processes one thing and only does this once.

It does this for the `<style>` tag and the `style` attribute on `<img src="https://via.placeholder.com/160x60"...`

On `Once` we collect all the values for custom properties.

**Comment by lubomirblazekcz** [comment]
Ok no worries, I've actually came with a workaround for my usecase. But I've created this issue in case if it is something that can be fixed perhaps :)

**Comment by romainmenke** [comment]
@ai I missed `Document` in the PostCSS API but it does seem interesting and relatively simple to support.

We still have a few plugins with `Once` like `custom-properties` because these attempt to mimic how CSS works in a browser.

This example can't be processed with the new visitor API.
To mimic browser behaviour we first need to gather all custom properties.

```css
.a {
	color: var(--color);
}

:root {
	--color: red;
}
```

I can update our plugin to use `Document` instead of `Once` and combine all nodes with type `root`.

```js
Once: (root) => {
	customProperties = getCustomPropertiesFromRoot(root, { preserve });
},
```

becomes :

```js
Document: (document) => {
	customProperties = new Map();
	document.nodes.forEach((node) => {
		if (node.type !== 'root') {
			return;
		}

		for (const [key, value] of getCustomPropertiesFromRoot(node, { preserve }).entries()) {
			customProperties.set(key, value);
		}
	});
},
```

Because I don't know the API I also don't know if this will cause issues with other syntaxes or plugins.

The docs also say that this API is still experimental.
Is it safe to use in something like `postcss-preset-env`?
