### ISSUE TITLE
[css-has-pseudo] produces a weird long attribute

### ISSUE THREAD

**Issue by lubomirblazekcz** [csstools/postcss-plugins#597]
### Bug description

css-has-pseudo is not working as expected a long attribute is generated `csstools-has-2q-33-2s-3d-1m-2w-2p-37-14-1m-2u-33-2r-39-37-15`

I don't think this is correct? Here is a working demo https://stackblitz.com/edit/vitejs-vite-o74i8p

### Source CSS

```css
body:has(:focus) {
  background-color: yellow;
}
```

### Expected CSS

```css
body[\:has\(\:focus\)] {
  background-color: yellow;
}

body:has(:focus) {
  background-color: yellow;
}
```

### Actual CSS

```css
.js-has-pseudo [csstools-has-2q-33-2s-3d-1m-2w-2p-37-14-1m-2u-33-2r-39-37-15]:not(does-not-exist) {
  background-color: yellow;
}

body:has(:focus) {
  background-color: yellow;
}
```

### What plugin are you experiencing this issue on?

CSS Has Pseudo

### Plugin version

4.0.1

### Node Version

16, 18

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
