### ISSUE TITLE
`postcss-dir-pseudo-class` has poor support for complex selectors

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#60]
### Bug description

Complex selectors in `postcss-dir-pseudo-class` have unexpected output.

related : https://github.com/csstools/postcss-dir-pseudo-class/issues/3

### Source CSS

```css
button > :dir(ltr) {
	order: 36;
}
```

### Expected CSS

```css
button > [dir="ltr"],
[dir="ltr"] button > :not([dir="rtl"]) {
	order: 36;
}
```

or 

```css
[dir="ltr"] button > * {
	order: 36;
}
```

Not a 100% sure that this expected CSS is fully correct.

### Actual CSS

```css
[dir="ltr"] button >  {
	order: 36;
}
```

### Does it happen with `npx <plugin-name> minimal-example.css`?

Yes

### Extra config

N/A

### What plugin are you experiencing this issue on?

PostCSS Dir Pseudo Class

### Plugin version

6.0.0

### What OS are you experiencing this on?

macOS

### Node Version

16

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR
