### ISSUE TITLE
plugin for `random()`

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#601]
### What would you want to propose?

_TODO_

### Suggested solution

_TODO_

### Additional context

- https://github.com/w3c/csswg-drafts/issues/2826
- might be part of `css-values-5` : https://drafts.csswg.org/css-values-5/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
Closing for now, waiting on the final specification

**Comment by romainmenke** [comment]
https://w3c.github.io/csswg-drafts/css-values-5/#randomness

**Comment by Antonio-Laguna** [comment]
The issue I have with this is that this would be a random value at generation time vs at consumed time unless we go the JS way

**Comment by romainmenke** [comment]
It can not even be random at generation time, that would make CSS builds indeterministic.
Each value must be pseudo random from a seed that exists within the CSS source.
Building twice must have the same outcome.

It can work as a fallback, but never as a polyfill.

**Comment by romainmenke** [comment]
> The per-element keyword causes the [random()](https://w3c.github.io/csswg-drafts/css-values-5/#funcdef-random) function to generate a different value on each element the function is applied to, rather than resolving to a single value per usage in the stylesheet.

This is not something we can do 🤔 

```css
.random {
  width: random(per-element, 100px, 500px);
}
```

Would become :

```css
.random {
  width: 372px;
}
```

But that is the same for each element.

Maybe counters?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters

**Comment by Antonio-Laguna** [comment]
🤔

**Comment by brandonmcconnell** [comment]
@romainmenke re this:
> Each value must be pseudo random from a seed that exists within the CSS source.
Building twice must have the same outcome.

My understanding of `random()` is that it is expected to have a different value for each pageload and that the same value only persists for the current sessions.

Is that not the case? Where in the spec is that, if you know?

**Comment by romainmenke** [comment]
> My understanding of random() is that it is expected to have a different value for each pageload and that the same value only persists for the current sessions.

That is correct :)

I was working under the assumption to include this in PostCSS Preset Env.

If we include a non-deterministic plugin there we would break a lot of things.
Too many people are running build systems that must have a deterministic outcome.

A standalone plugin, not included in PostCSS Preset Env would not have this constraint.

-----------

My initial idea was to have a plugin that helps authors with a semi-random fallback value.
The result would still feel random for end users in some cases and it would help CSS authors by not having to provide manual fallback values.

----------

A second idea I had was to use the DOM itself as a source of entropy.

```css
:root:has(:nth-child(...) :nth-child(...) ...) {
  --random-1: 1;
  --random-2: 2;
  --random-3: 3;
}

:root:has(:nth-child(...) :nth-child(...) ...) {
  --random-1: 2;
  --random-2: 3;
  --random-3: 1;
}

:root:has(:nth-child(...) :nth-child(...) ...) {
  --random-1: 3;
  --random-2: 1;
  --random-3: 2;
}

.foo {
  /* really quick maths, likely very broken/incorrect */
  width: clamp(100px, calc(100px + (var(--random-1) * (300px - 100px))), 300px)
  width: random(100px, 300px);
}
```

**Comment by romainmenke** [comment]
The technique above could also be done without `:has` with some tweaks.

**Comment by romainmenke** [comment]
```css
:nth-child(2) {
  --random-1: 1;
}

:nth-child(2n+1) {
  --random-1: 2;
}

:nth-child(2n+2) {
  --random-1: 3;
}

:nth-child(2n+3) {
  --random-1: 4;
}

:nth-child(3) {
  --random-2: 1;
}

:nth-child(3n+1) {
  --random-2: 2;
}

:nth-child(3n+2) {
  --random-2: 3;
}

:nth-child(3n+3) {
  --random-2: 4;
}

/* ... */

.foo {
  /* really quick maths, likely very broken/incorrect */
  width: clamp(100px, calc(100px + (((var(--random-1) + var(--random-2) + var(--random-3)) / 3) * (300px - 100px))), 300px);
  width: random(100px, 300px);
}
```
