### ISSUE TITLE
`postcss-double-position-gradients` does not support `preserve: true` with CSS variables

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#61]
### Bug description

When assign a gradient value to a variable with `preserve: true` the actual value will be invalid.

### Source CSS

```css
:root {
	--some-var: linear-gradient(90deg, black 25% 50%, blue 50% 75%);
}
```

### Expected CSS

```css
:root {
	--some-var: linear-gradient(90deg, black 25%, black 50%, blue 50%, blue 75%);
}

@supports (linear-gradient(90deg, black 25% 50%, blue 50% 75%)) {
	:root {
		--some-var: linear-gradient(90deg, black 25% 50%, blue 50% 75%);
	}
}
```

### Actual CSS

```css
:root {
	--some-var: linear-gradient(90deg, black 25%, black 50%, blue 50%, blue 75%);
	--some-var: linear-gradient(90deg, black 25% 50%, blue 50% 75%);
}
```

### Does it happen with `npx <plugin-name> minimal-example.css`?

Yes

### Extra config

`preserve` set to `true`

### What plugin are you experiencing this issue on?

PostCSS Double Position Gradients

### Plugin version

3.0.1

### What OS are you experiencing this on?

macOS

### Node Version

16

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR
