### ISSUE TITLE
postcss-logical doesn't correctly transform compound selectors

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#621]
### Bug description

I would expect transformed compound selectors to work.

### Source CSS

```css
.alpha::before {
	margin-inline-start: 10px;
}
```

### Expected CSS

```css
.alpha:dir(ltr)::before {
	margin-left: 10px
}
```

### Actual CSS

```css
.alpha::before:dir(ltr) {
	margin-left: 10px
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Logical

### Plugin version

5.0.4

### Node Version

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR
