### ISSUE TITLE
:focus-visible conflicts with :has

### ISSUE THREAD

**Issue by edoardocavazza** [csstools/postcss-plugins#729]
### Bug description

Transformation of `:has(:focus-visible)` generates invalid CSS when using postcss-preset-env. Probably, it is a problem with plugins execution order.

### Source CSS

```css
div:has(:focus-visible) {
  outline: solid 2px red;
}
```

### Expected CSS

```css
div[\:has\(\.focus-visible\)] {
  outline: solid 2px red;
}
```

### Actual CSS

```css
div[\:has\(.focus-visible\)] {
  outline: solid 2px red;
}
```
^ note that the `.` in `.focus-visible` is not escaped.

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

7.19.4

### What OS are you experiencing this on?

macOS

### Node Version

v17.9.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
