### ISSUE TITLE
CSS with extensions not correctly transforming

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#738]
My 2:20-morning brain could not think to install `postcss-env-function` separately. Thank you.

I tried installing the <del>beta</del> <ins>alpha</ins> and `postcss-env-function`. I do not see the fix succeed.

Has my 3:20-morning brain done anything wrong?

### Source & Config

<details><summary><code>package.json</code> (abbreviated)</summary>

```json
  "peerDependencies": {
    "commander": "^9.4.1",
    "cssnano": "^5.1.14",
    "js-yaml": "^4.1.0",
    "merge-lite": "^1.0.2",
    "node-cmd": "^5.0.0",
    "npm-watch": "^0.11.0",
    "postcss": "^8.4.18",
    "postcss-banner": "^4.0.1",
    "postcss-cli": "^10.0.0",
    "postcss-extend": "^1.0.5",
    "postcss-env-function": "4.0.6",
    "postcss-import": "^15.0.0",
    "postcss-preset-env": "^8.0.0-alpha.1",
    "postcss-replace": "^2.0.0"
  },
  "devDependencies": {
    "@frctl/fractal": "^1.5.13",
    "@frctl/mandelbrot": "^1.10.1"
  },
```

No `dependencies`. Long story. Temporary. Does it matter?

</details>

<details><summary><code>npm list</code></summary>

```bash
➜  Core-Styles git:(dev--task/form-patterns--task/base-cms-portal-header) ✗ npm list postcss-env-function
@tacc/core-styles@v0.11.0-30-g66400cb /Users/wbomar/Code/Core-Styles
└── postcss-env-function@4.0.6

➜  Core-Styles git:(dev--task/form-patterns--task/base-cms-portal-header) ✗ npm list postcss-custom-selectors           
@tacc/core-styles@v0.11.0-30-g66400cb /Users/wbomar/Code/Core-Styles
└─┬ postcss-preset-env@8.0.0-alpha.1
  └── postcss-custom-selectors@7.0.0
```

</details>

<details><summary><code>src/.postcssrc.yml</code></summary>

```yaml
plugins:
  postcss-import:
    path:
      - src/lib
  postcss-extend: {}
  postcss-env-function:
    importFrom:
      - src/lib/_themes/default.json
  postcss-preset-env:
    stage: false
    features:
      custom-media-queries: true
      media-query-ranges: true
      custom-selectors: true
  cssnano:
    preset:
      - default
      - discardDuplicates:
          exclude: true
        mergeRules:
          exclude: true
  postcss-banner:
    banner: '@tacc/core-styles v0.11.0-30-g66400cb+ | MIT | github.com/TACC/Core-Styles'
    inline: true
    important: true
  postcss-replace:
    pattern: ../../fonts/
    data:
      replaceAll: fonts/
```

</details>

<details><summary><code>src/.../c-button.css</code></summary>

```postcss
@custom-selector :--disabled :disabled,[disabled];

.c-button {
  display: inline-block;

  box-sizing: border-box;

  border-width: var(--global-border-width--normal);
  border-style: solid;
}

.c-button:not(:--disabled) {
  cursor: pointer; /* WARNING: Opinionated */
}
```

</details>

### No `@import`

✓ The `@custom-selector` is parsed away.

<details><summary><code>dist/c-button.css</code></summary>

```css
/*! @tacc/core-styles v0.11.0-30-g66400cb+ | MIT | github.com/TACC/Core-Styles */.c-button{border-style:solid;border-width:var(--global-border-width--normal);box-sizing:border-box;display:inline-block}.c-button:not(:is(:disabled,[disabled])){cursor:pointer}
```

</details>

### Use `@import`

ⓧ The `@custom-selector` remains, unparsed.

<details><summary><code>src/.../core-styles.base.css</code></summary>

```postcss
/*! core-styles.base.css */
@import url("./components/c-button.css") layer(components);
```

</details>

<details><summary><code>dist/core-styles.base.css</code></summary>

```css
/*! @tacc/core-styles v0.11.0-30-g66400cb+ | MIT | github.com/TACC/Core-Styles */
/*! core-styles.base.css */@layer components{@custom-selector :--disabled :disabled,[disabled];.c-button{border-style:solid;border-width:var(--global-border-width--normal);box-sizing:border-box;display:inline-block}.c-button:not(:--disabled){cursor:pointer}}
```

</details>

_Originally posted by @wesleyboar in https://github.com/csstools/postcss-plugins/issues/481#issuecomment-1334979196_

**Comment by romainmenke** [comment]
@wesleyboar I've take your report and created a separate issue to keep the other thread on topic.

Can you verify a few things?

What is the output without `cascade-layers` but with `@import`?

This in your `base.css` :

```css
/*! core-styles.base.css */
@import url("./components/c-button.css");
```

What is the version of `@csstools/postcss-cascade-layers` ?

```
npm list @csstools/postcss-cascade-layers
```

**Comment by wesleyboar** [comment]
Okay. Yes.

<details><summary>The output—sans cascade-layers, with import—is correct custom-selectors parsing.</summary>

**Input `base.css`**
```
/*! core-styles.base.css */
@import url("./components/c-button.css");
```

**Output `base.css`**
```
/*! @tacc/core-styles v0.11.0-30-g66400cb+ | MIT | github.com/TACC/Core-Styles */
/*! core-styles.base.css */.c-button{border-style:solid;border-width:var(--global-border-width--normal);box-sizing:border-box;display:inline-block}.c-button:not(:is(:disabled,[disabled])){cursor:pointer}
```

</details>

<details><summary>My cascade-layers is at v2.0.0.</summary>

**`npm list @csstools/postcss-cascade-layers`**
```
➜  Core-Styles git:(dev--task/form-patterns--task/base-cms-portal-header) ✗ npm list @csstools/postcss-cascade-layers
@tacc/core-styles@v0.11.0-30-g66400cb /Users/wbomar/Code/Core-Styles
└─┬ postcss-preset-env@8.0.0-alpha.1
  └── @csstools/postcss-cascade-layers@2.0.0
```

</details>

**Comment by romainmenke** [comment]
Unminified output : 

```css
.c-button {
	border-style: solid;
	border-width: var(--global-border-width--normal);
	box-sizing: border-box;
	display: inline-block
}

.c-button:not(:is(:disabled, [disabled])) {
	cursor: pointer
}
```

---------

🤔 Something is indeed not working here but I can't reproduce it within our repo.

```css
/* styles.css (entrypoint) */
@import url(./imports/extensions.css) layer(extensions);
@import url(./imports/components.css) layer(components);
```

```css
/* extensions.css */
@custom-media --dark (prefers-color-scheme: dark);
@custom-media --light (prefers-color-scheme: light);
@custom-media --tablet (width >= 768px);

@custom-selector :--h h1, h2, h3, h4, h5, h6;
@custom-selector :--button button, input[type="submit"];

:root {
	--color-red: red;
	--color-blue: blue;
}
```

```css
/* components.css */
:--button {
	color: var(--color-red);
}

@media (--dark) {
	:--button {
		color: var(--color-blue);
	}
}
```

Becomes :

```css
:root {
	--color-red: red;
	--color-blue: blue;
}
button:not(.does-not-exist):not(#\#) {
	color: red;
	color: var(--color-red);
}
input[type="submit"]:not(#\#) {
	color: red;
	color: var(--color-red);
}
@media (prefers-color-scheme: dark) {
	button:not(.does-not-exist):not(#\#) {
		color: blue;
		color: var(--color-blue);
	}
	input[type="submit"]:not(#\#) {
		color: blue;
		color: var(--color-blue);
	}
}
```

All extensions resolved correctly :
- custom properties
- custom media
- custom selectors

--------

I am currently working a fix for the interaction with CSS Nesting so maybe that one also fixes this issue?

Alternatively it would be best to have a minimal reproduction.
Ideally something we can clone locally and inspect in detail.

**Comment by romainmenke** [comment]
Nevermind, I noticed what is happening :)

```
  postcss-preset-env:
    stage: false
    features:
      custom-media-queries: true
      media-query-ranges: true
      custom-selectors: true
```

You have disabled all features except those three.
Those three features do not support Cascade Layers.

It is currently the Cascade Layers plugin which removes all `@layer` rules.
After this the other plugins work as expected.

Since you disabled Cascade Layers nothing will work.

----

> I am currently working a fix for the interaction with CSS Nesting so maybe that one also fixes this issue?

This change will allow your setup to work.
