### ISSUE TITLE
[postcss-preset-env] Does the `enableClientSidePolyfills` option suppose to inject required JS polyfills automatically?

### ISSUE THREAD

**Issue by KarimTayel** [csstools/postcss-plugins#744]
Hi,

I'm using `Webpack` with `PostCSS` to compile and transform my `SASS` files as needed using `sass-loader` and `postcss-loader`.

Here is my `PostCSS` config:

```javascript
module.exports = {
  plugins: [
    [
      'postcss-preset-env',
      {
        stage: 2,
        minimumVendorImplementations: 0,
        autoprefixer: false,
        enableClientSidePolyfills: true,
      },
    ],
    'autoprefixer',
  ],
};
```

Setting `enableClientSidePolyfills` to `true` doesn't do anything. As I understand it's supposed to enable any feature that would need an extra browser library to be loaded into the page for it to work.

Code Example:

```sass
a:not([class]) {
  &:focus-visible {
    outline: 1px dotted colors.$link-focus-color;
  }
}
```

Output:

```css
a:not([class]).focus-visible.js-focus-visible, .js-focus-visible a:not([class]).focus-visible {
  outline: 1px dotted #ff6347;
}

a:not([class]):focus-visible {
  outline: 1px dotted #ff6347;
}
```

As you can see the `focus-visible` classes are added but the required JavaScript polyfill isn't loaded to make it work when navigating links using the keyboard.

---

I'm using:

- webpack `5.75.0`
- postcss `8.4.20`
- postcss-loader `7.0.2`
- postcss-preset-env `8.0.0-alpha.1`
