### ISSUE TITLE
Border color is not set in Next.js production mode

### ISSUE THREAD

**Issue by AdiPol1359** [csstools/postcss-plugins#766]
### Reproduction link

https://github.com/AdiPol1359/oklab-crash-reproduction

### Bug description

When the page is built and run in production mode, the border color is not set for the elements. This issue doesn't occur in development mode.

dev:
![dev](https://user-images.githubusercontent.com/27779154/211097655-570ff50f-3b3a-42ea-91f1-32afe21255da.png)
prod:
![prod](https://user-images.githubusercontent.com/27779154/211097659-7e5f2648-b882-4ba8-a641-2ff6fc72de45.png)

### Actual Behavior

Border color doesn't change to RGB color.

### Expected Behavior

Border color should change to RGB color.

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

No

### What plugin are you experiencing this issue on?

PostCSS OKLab Function

### Plugin version

1.1.1

### What OS are you experiencing this on?

Windows

### Node Version

18.12.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @AdiPol1359,
Thank you for reaching out!

_At first glance this does not seem to be an issue with the PostCSS plugin._

Is it possible that building for production also runs a CSS minifier?
And is it possible that such a CSS minifier removes fallback declarations?

This is a fallback :

```css
.foo {
  color: red; /* fallback */
  color: color(displayP3 1 0 0);
}
```

Minifier removes fallbacks :

```css
.foo {
  color: color(displayP3 1 0 0);
}
```

**Comment by romainmenke** [comment]
@AdiPol1359 What happens when you manually add something like :

```css
.foo {
  color: red; /* fallback */
  color: blue;
}
```

Does a production build remove `color: red; /* fallback */` ?

**Comment by AdiPol1359** [comment]
> @AdiPol1359 What happens when you manually add something like :
> 
> ```css
> .foo {
>   color: red; /* fallback */
>   color: blue;
> }
> ```
> 
> Does a production build remove `color: red; /* fallback */` ?

This issue only occurs with border-color. For example background-color, or text color is replaced fine, so I don't think so. I'll test it later.

**Comment by romainmenke** [comment]
Can you then also try this :

```css
.foo {
  border-color: 1px solid red;
  border-color: 1px solid blue;
}
```

The important part is having a hard coded fallback in your code.
This allows you to verify if something is removing CSS or if something is not adding it.

**Comment by AdiPol1359** [comment]
> 

I created new classes in CSS:
```css
.foo1 {
  color: red; /* fallback */
  color: blue;
}
.foo2 {
  border-color: 1px solid red; /* fallback */
  border-color: 1px solid blue;
}
```
Dev mode:
![image](https://user-images.githubusercontent.com/27779154/211146335-24fe23f3-92bf-43a5-ba0f-25a5d1feb822.png)
Prod mode:
![image](https://user-images.githubusercontent.com/27779154/211146389-32616358-9b08-4e6c-9ff7-aae7ff94a5dd.png)

From what I can see, Next removed ``fallback`` style from class ``foo2`` after build, but didn't remove it in ``foo1``. This is the CSS output after build:
```css
.foo{border:2px solid color(display-p3 .52783 .30092 .68693)}.foo1{color:red;color:blue}.foo2{border-color:1px solid blue}
```

**Comment by AdiPol1359** [comment]
> > 
> 
> @romainmenke I created new classes in CSS:
> 
> ```css
> .foo1 {
>   color: red; /* fallback */
>   color: blue;
> }
> .foo2 {
>   border-color: 1px solid red; /* fallback */
>   border-color: 1px solid blue;
> }
> ```
> 
> Dev mode: ![image](https://user-images.githubusercontent.com/27779154/211146335-24fe23f3-92bf-43a5-ba0f-25a5d1feb822.png) Prod mode: ![image](https://user-images.githubusercontent.com/27779154/211146389-32616358-9b08-4e6c-9ff7-aae7ff94a5dd.png)
> 
> From what I can see, Next removed `fallback` style from class `foo2` after build, but didn't remove it in `foo1`. This is the CSS output after build:
> 
> ```css
> .foo{border:2px solid color(display-p3 .52783 .30092 .68693)}.foo1{color:red;color:blue}.foo2{border-color:1px solid blue}
> ```

I created an invalid property value, but after fixing the result is the same:
![image](https://user-images.githubusercontent.com/27779154/211146826-210c17fd-4231-4f4f-9e4d-b664b8621e43.png)
![image](https://user-images.githubusercontent.com/27779154/211146848-ae5ab335-d50a-420c-ab05-d5cbe9390208.png)
```css
.foo{border:2px solid color(display-p3 .52783 .30092 .68693)}.foo1{color:red;color:blue}.foo2{border:1px solid blue}
```
