### ISSUE TITLE
postcss-custom-media stopped working with version 9.x

### ISSUE THREAD

**Issue by sebastianhelbig** [csstools/postcss-plugins#823]
### Bug description

After upgrading to postcss-custom media 9.x, the custom media queries are not replaced anymore. Going back to version 8.0.2 and everything works fine again.

### Actual Behavior

```css
@custom-media --md-min (min-width: 768px);
@media (--md-min) {
  .profile {
    display: grid;
  }
}
/* becomes */
@media (--md-min) {
  ._profile_11s99x {
    display: grid;
  }
}
````

### Expected Behavior

```css
@custom-media --md-min (min-width: 768px);
@media (--md-min) {
  .profile {
    display: grid;
  }
}
/* becomes */
@media (min-width: 768px) {
  ._profile_11s99x {
    display: grid;
  }
}
````
### Extra config

```
"postcss-custom-media": "9.1.1",
"postcss-import": "15.1.0",
"postcss-modules-values": "4.0.0",
"postcss-normalize": "10.0.1",
"postcss-preset-env": "8.0.1",
"postcss": "8.4.21",
```

We are using css-modules with the following plugin config:
```
plugins: [
  postcssNormalize(),
  postcssImport({ path: ['node_modules', '../../node_modules'] }),
  postcssModulesValues(),
  postcssPresetEnv({
    browsers: [...targets.browsers],
    features: {
      'custom-media-queries': true,
      'nesting-rules': true,
    },
  }),
],
```

### What plugin are you experiencing this issue on?

postcss-custom-media

### Plugin version

9.1.1

### What OS are you experiencing this on?

Mac and Linux

### Node Version

18.13.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
