### ISSUE TITLE
postcss-logical, v8 breaks logical properties semantic

### ISSUE THREAD

**Issue by felixmosh** [csstools/postcss-plugins#832]
### What would you want to propose?

In previous version (v7) the css that was generated supports both direction (like it should be with logical properties).

```css
// this
.test {
  margin-inline-start: 1rem;
}

// v7
[dir="ltr"] .test {
  margin-left: 1rem;
}
[dir="rtl"] .test {
  margin-right: 1rem;
}
```
This preserves the same semantics of logical properties, the "same" css code supports both directions.

Starting `v8`, it generates only one direction (as specified in the plugin options), this breaks the semantics above.

### Suggested solution

Maybe it is possible to add an plugin option to generate both direction at once, like it was in `v7`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR
