### ISSUE TITLE
[postcss-nesting] Option to turn off extra tabs on nested CSS

### ISSUE THREAD

**Issue by Woedenaz** [csstools/postcss-plugins#833]
### What would you want to propose?

Currently, when running nested CSS through `postcss-nesting` the output CSS includes extra tabs in relation to the amount of tabs on the original nested CSS.

This is shown in the example given on the `postcss-nesting` page:

```css
.foo {
	color: red;

	&:hover {
		color: green;
	}

	> .bar {
		color: blue;
	}

	@media (prefers-color-scheme: dark) {
		color: cyan;
	}
}

/* becomes */

.foo {
	color: red;
}
.foo:hover {
		color: green;
	}
.foo > .bar {
		color: blue;
	}
@media (prefers-color-scheme: dark) {
	.foo {
		color: cyan;
}
	}
```

The middle two properties are given 1 extra tab and the final two right curly brackets are given incorrect tabs.

While I understand why some would prefer this sort of output, I find it messy and not indicative of the sort of CSS I would write were I not using nesting.

Additionally, when using older versions of `postcss-nesting`, for instance version 4.0.1 used in the deprecated `postcss-cssnext`, these extra tabs did not happen.

### Suggested solution

Give an option to turn off these extra tabs. Since older versions of `css-nexting` did not include these extra tabs, it is likely this is possible to some degree.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR
