### ISSUE TITLE
max- and min- logical sizes not being transformed

### ISSUE THREAD

**Issue by thewilkybarkid** [csstools/postcss-plugins#858]
### Bug description

`(max|min)-(block|inline)-size` aren't being transformed like `(block|inline)-size`.

### Source CSS

```css
.foo {
  block-size: 1px;
  inline-size: 2px;
  min-block-size: 3px;
  max-block-size: 4px;
  min-inline-size: 5px;
  max-inline-size: 6px;
}
```

### Expected CSS

```css
.foo {
  height: 1px;
  width: 2px;
  min-height: 3px;
  max-height: 4px;
  min-width: 5px;
  max-width: 6px;
}
```

### Actual CSS

```css
.foo {
  height: 1px;
  width: 2px;
  min-block-size: 3px;
  max-block-size: 4px;
  min-inline-size: 5px;
  max-inline-size: 6px;
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Logical

### Plugin version

6.0.1

### What OS are you experiencing this on?

Linux, macOS

### Node Version

18.14.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
