### ISSUE TITLE
Missing fallback on color function since color changes

### ISSUE THREAD

**Issue by carlosjeurissen** [csstools/postcss-plugins#920]
### Bug description

Something happened in the dependencies of one or multiple of below plugins. Just reinstalling them (let them use the latest semvar dependencies), gives different results.

postcss-color-function v2.1.0-v2.2.0
postcss-hwb-function v2.1.1-v2.2.0
postcss-oklab-function v2.1.0-v2.2.0
postcss-lab-function v5.1.0-v5.2.0

The color(display-p3) fallback is completely skipped. Even tho it has better browser support (safari 15 vs 15.4) than the oklab and oklch functions.

### Source CSS

```css
p {
  color: oklab(72.322% -0.0465 -0.1150);
  color: oklch(72.322% 0.12403 247.996);
}

.color-lab {
  color: lab(40% 56.6 39);
}

.color-lch {
  color: lch(40% 68.735435 34.568626);
}
```

### Expected CSS

```css
p {
  color: rgb(98, 172, 239);
  color: color(display-p3 0.45207 0.66555 0.91656);
  color: oklab(72.322% -0.0465 -0.1150);
  color: oklch(72.322% 0.12403 247.996);
}

.color-lab {
  color: rgb(179, 35, 35);
  color: color(display-p3 0.64331 0.19245 0.16771);
  color: lab(40% 56.6 39);
}

.color-lch {
  color: rgb(179, 35, 35);
  color: color(display-p3 0.64331 0.19245 0.16771);
  color: lch(40% 68.735435 34.568626);
}
```

### Actual CSS

```css
p {
  color: rgb(98, 172, 239);
  color: oklab(72.322% -0.0465 -0.1150);
  color: oklch(72.322% 0.12403 247.996);
}

.color-lab {
  color: rgb(179, 35, 35);
  color: lab(40% 56.6 39);
}

.color-lch {
  color: rgb(179, 35, 35);
  color: lch(40% 68.735435 34.568626);
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Color Function

### Plugin version

2.1.0 to 2.2.0

### Node Version

19.8.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @carlosjeurissen,
Thank you for reporting this!

> Just reinstalling them (let them use the latest semver dependencies), gives different results.

Can you clarify this?

Which versions give which results?
Are any of the results correct, or always wrong?

**Comment by romainmenke** [comment]
Can already confirm that your particular `oklch` value doesn't get a fallback on the playground :

<img width="1289" alt="Screenshot 2023-04-05 at 12 55 07" src="https://user-images.githubusercontent.com/11521496/230060578-4606756c-5767-4195-a05d-ad4783ed42e1.png">

```css
p {
  color: rgb(98, 172, 239);
  color: oklch(72.322% 0.12403 247.996);
}

.color-lab {
  color: rgb(179, 35, 35);
}

.color-lch {
  color: rgb(179, 35, 35);
}
```

**Comment by romainmenke** [comment]
@carlosjeurissen Can you test with this CSS :

```css
.color-lab {
  color: lab(40% 80 39);
}
```

That color doesn't fit within the `srgb` color gamut, the others do and don't need a `display-p3` fallback.
