### ISSUE TITLE
`:not(:focus-within)` creating problems

### ISSUE THREAD

**Issue by shgysk8zer0** [csstools/postcss-plugins#955]
### Bug description

I do not use the polyfill that adds the `focus-within` attribute. It'd be fine to add the `[focus-within]` rule, but the `:not(:focus-within)` becoming `:not([focus-within])` causes the rule to always match.

I have disabled it for now using the config:

```
{
	features: {
		'focus-within-pseudo-class': false,
	}
}
```

But it was an unwanted change, and requires me to update multiple sites with this added step for things to work as expected.

### Source CSS

```css
.visually-hidden:not(:focus-within) {
  border:none;
 contain:layout style paint;
 height:0;
 margin:0;
 overflow:hidden;
 padding:0;
 width:0;
}
```

### Expected CSS

```css
.visually-hidden:not(:focus-within, [focus-within]) {
  border:none;
 contain:layout style paint;
 height:0;
 margin:0;
 overflow:hidden;
 padding:0;
 width:0;
}
```

### Actual CSS

```css
.visually-hidden:not([focus-within]) {
 border:none;
 contain:layout style paint;
 height:0;
 margin:0;
 overflow:hidden;
 padding:0;
 width:0
}
.visually-hidden:not(:focus-within) {
 border:none;
 contain:layout style paint;
 height:0;
 margin:0;
 overflow:hidden;
 padding:0;
 width:0
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### Debug output

NA

### Extra config

```js
module.exports = {
	map: { inline: false },
	plugins: [
		require('postcss-import'),
		require('postcss-url'),
		require('postcss-import-url'),
		require('postcss-preset-env'),
		require('postcss-discard-comments'),
		require('postcss-custom-properties'),
		require('postcss-media-minmax'),
		require('cssnano'),
	]
};
```

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

7.4.3

### What OS are you experiencing this on?

Linux

### Node Version

18.13.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
