### ISSUE TITLE
postcss-preset-env did not adhere to the browserslist configuration

### ISSUE THREAD

**Issue by ftpilot** [csstools/postcss-plugins#968]
### Bug description

postcss.config.mjs:
```js
import postcssPresetEnv from 'postcss-preset-env'
export default {
  plugins: [
    postcssPresetEnv({
      stage: 0,
    }),
  ],
}
```

And there are two `stage 2` features(Chrome 100 doesn't support any of them and Chrome 105 supports all of them):
- [hwb() Function](https://cssdb.org/#hwb-function)
- [:has() Relational Pseudo-Class](https://cssdb.org/#has-pseudo-class)

When browserslist config is `Chrome 105`, it outputs:
```css
div:has(p) {color: red;}
p {color: hwb(120 44% 50%);}
```

When browserslist config is `Chrome 100`, it outputs:
```css
div:has(p) {color: red;}
p {color: rgb(112, 128, 112);}
```

It means that the hwb-function plugin worked, but the has-pseudo-class plugin did not work.

If we want to use this polyfill in `Chrome 100`, we must manually configure this feature.
```js
{
  stage: 0,
  features: {
    'has-pseudo-class': true,
  },
}
```

So, I think there's a bug.

### Source CSS

```css
div:has(p) {color: red;}
p {color: hwb(120 44% 50%);}
```

### Expected CSS

```css
.js-has-pseudo [csstools-has-2s-2x-3a-1m-2w-2p-37-14-34-15]:not(does-not-exist):not(does-not-exist) {color: red;}
p {color: rgb(112, 128, 112);}
```

### Actual CSS

```css
div:has(p) {color: red;}
p {color: rgb(112, 128, 112);}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

^8.3.2

### What OS are you experiencing this on?

macOS

### Node Version

16

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR
